import {
  home01SmJpgImg,
  home01SmAvifImg,
  home01MdJpgImg,
  home01MdAvifImg,
  home01LgJpgImg,
  home01LgAvifImg,
  home01XlJpgImg,
  home01XlAvifImg,
  home02SmJpgImg,
  home02SmAvifImg,
  home02MdJpgImg,
  home02MdAvifImg,
  home02LgJpgImg,
  home02LgAvifImg,
  home02XlJpgImg,
  home02XlAvifImg,
  home03SmJpgImg,
  home03SmAvifImg,
  home03MdJpgImg,
  home03MdAvifImg,
  home03LgJpgImg,
  home03LgAvifImg,
  home03XlJpgImg,
  home03XlAvifImg,
  home04SmJpgImg,
  home04SmAvifImg,
  home04MdJpgImg,
  home04MdAvifImg,
  home04LgJpgImg,
  home04LgAvifImg,
  home04XlJpgImg,
  home04XlAvifImg,
  home05SmJpgImg,
  home05SmAvifImg,
  home05MdJpgImg,
  home05MdAvifImg,
  home05LgJpgImg,
  home05LgAvifImg,
  home05XlJpgImg,
  home05XlAvifImg,
  home06SmJpgImg,
  home06SmAvifImg,
  home06MdJpgImg,
  home06MdAvifImg,
  home06LgJpgImg,
  home06LgAvifImg,
  home06XlJpgImg,
  home06XlAvifImg,
  home07SmJpgImg,
  home07SmAvifImg,
  home07MdJpgImg,
  home07MdAvifImg,
  home07LgJpgImg,
  home07LgAvifImg,
  home07XlJpgImg,
  home07XlAvifImg,
  home08SmJpgImg,
  home08SmAvifImg,
  home08MdJpgImg,
  home08MdAvifImg,
  home08LgJpgImg,
  home08LgAvifImg,
  home08XlJpgImg,
  home08XlAvifImg,
  vinosAnforaSmPngImg,
  vinosAnforaContraSmPngImg,
  vinosAnforaSmAvifImg,
  vinosAnforaContraSmAvifImg,
  vinosAnforaMdPngImg,
  vinosAnforaContraMdPngImg,
  vinosAnforaMdAvifImg,
  vinosAnforaContraMdAvifImg,
  vinosAnforaLgPngImg,
  vinosAnforaContraLgPngImg,
  vinosAnforaLgAvifImg,
  vinosAnforaContraLgAvifImg,
  vinosAnforaXlPngImg,
  vinosAnforaContraXlPngImg,
  vinosAnforaXlAvifImg,
  vinosAnforaContraXlAvifImg,
  vinosGalloSmPngImg,
  vinosGalloContraSmPngImg,
  vinosGalloSmAvifImg,
  vinosGalloContraSmAvifImg,
  vinosGalloMdPngImg,
  vinosGalloContraMdPngImg,
  vinosGalloMdAvifImg,
  vinosGalloContraMdAvifImg,
  vinosGalloLgPngImg,
  vinosGalloContraLgPngImg,
  vinosGalloLgAvifImg,
  vinosGalloContraLgAvifImg,
  vinosGalloXlPngImg,
  vinosGalloContraXlPngImg,
  vinosGalloXlAvifImg,
  vinosGalloContraXlAvifImg,
  vinosVillaSmPngImg,
  vinosVillaContraSmPngImg,
  vinosVillaSmAvifImg,
  vinosVillaContraSmAvifImg,
  vinosVillaMdPngImg,
  vinosVillaContraMdPngImg,
  vinosVillaMdAvifImg,
  vinosVillaContraMdAvifImg,
  vinosVillaLgPngImg,
  vinosVillaContraLgPngImg,
  vinosVillaLgAvifImg,
  vinosVillaContraLgAvifImg,
  vinosVillaXlPngImg,
  vinosVillaContraXlPngImg,
  vinosVillaXlAvifImg,
  vinosVillaContraXlAvifImg,
  vinosPintoSmPngImg,
  vinosPintoContraSmPngImg,
  vinosPintoSmAvifImg,
  vinosPintoContraSmAvifImg,
  vinosPintoMdPngImg,
  vinosPintoContraMdPngImg,
  vinosPintoMdAvifImg,
  vinosPintoContraMdAvifImg,
  vinosPintoLgPngImg,
  vinosPintoContraLgPngImg,
  vinosPintoLgAvifImg,
  vinosPintoContraLgAvifImg,
  vinosPintoXlPngImg,
  vinosPintoContraXlPngImg,
  vinosPintoXlAvifImg,
  vinosPintoContraXlAvifImg,
  vinosNaranjoSmPngImg,
  vinosNaranjoContraSmPngImg,
  vinosNaranjoSmAvifImg,
  vinosNaranjoContraSmAvifImg,
  vinosNaranjoMdPngImg,
  vinosNaranjoContraMdPngImg,
  vinosNaranjoMdAvifImg,
  vinosNaranjoContraMdAvifImg,
  vinosNaranjoLgPngImg,
  vinosNaranjoContraLgPngImg,
  vinosNaranjoLgAvifImg,
  vinosNaranjoContraLgAvifImg,
  vinosNaranjoXlPngImg,
  vinosNaranjoContraXlPngImg,
  vinosNaranjoXlAvifImg,
  vinosNaranjoContraXlAvifImg,
  vinosMalbecSmPngImg,
  vinosMalbecContraSmPngImg,
  vinosMalbecSmAvifImg,
  vinosMalbecContraSmAvifImg,
  vinosMalbecMdPngImg,
  vinosMalbecContraMdPngImg,
  vinosMalbecMdAvifImg,
  vinosMalbecContraMdAvifImg,
  vinosMalbecLgPngImg,
  vinosMalbecContraLgPngImg,
  vinosMalbecLgAvifImg,
  vinosMalbecContraLgAvifImg,
  vinosMalbecXlPngImg,
  vinosMalbecContraXlPngImg,
  vinosMalbecXlAvifImg,
  vinosMalbecContraXlAvifImg,
  vinosSenorSmPngImg,
  vinosSenorContraSmPngImg,
  vinosSenorSmAvifImg,
  vinosSenorContraSmAvifImg,
  vinosSenorMdPngImg,
  vinosSenorContraMdPngImg,
  vinosSenorMdAvifImg,
  vinosSenorContraMdAvifImg,
  vinosSenorLgPngImg,
  vinosSenorContraLgPngImg,
  vinosSenorLgAvifImg,
  vinosSenorContraLgAvifImg,
  vinosSenorXlPngImg,
  vinosSenorContraXlPngImg,
  vinosSenorXlAvifImg,
  vinosSenorContraXlAvifImg,
  vinosRosadoSmPngImg,
  vinosRosadoContraSmPngImg,
  vinosRosadoSmAvifImg,
  vinosRosadoContraSmAvifImg,
  vinosRosadoMdPngImg,
  vinosRosadoContraMdPngImg,
  vinosRosadoMdAvifImg,
  vinosRosadoContraMdAvifImg,
  vinosRosadoLgPngImg,
  vinosRosadoContraLgPngImg,
  vinosRosadoLgAvifImg,
  vinosRosadoContraLgAvifImg,
  vinosRosadoXlPngImg,
  vinosRosadoContraXlPngImg,
  vinosRosadoXlAvifImg,
  vinosRosadoContraXlAvifImg,
  vinosSaucesSmPngImg,
  vinosSaucesContraSmPngImg,
  vinosSaucesSmAvifImg,
  vinosSaucesContraSmAvifImg,
  vinosSaucesMdPngImg,
  vinosSaucesContraMdPngImg,
  vinosSaucesMdAvifImg,
  vinosSaucesContraMdAvifImg,
  vinosSaucesLgPngImg,
  vinosSaucesContraLgPngImg,
  vinosSaucesLgAvifImg,
  vinosSaucesContraLgAvifImg,
  vinosSaucesXlPngImg,
  vinosSaucesContraXlPngImg,
  vinosSaucesXlAvifImg,
  vinosSaucesContraXlAvifImg,
  vinosBlancoSmPngImg,
  vinosBlancoContraSmPngImg,
  vinosBlancoSmAvifImg,
  vinosBlancoContraSmAvifImg,
  vinosBlancoMdPngImg,
  vinosBlancoContraMdPngImg,
  vinosBlancoMdAvifImg,
  vinosBlancoContraMdAvifImg,
  vinosBlancoLgPngImg,
  vinosBlancoContraLgPngImg,
  vinosBlancoLgAvifImg,
  vinosBlancoContraLgAvifImg,
  vinosBlancoXlPngImg,
  vinosBlancoContraXlPngImg,
  vinosBlancoXlAvifImg,
  vinosBlancoContraXlAvifImg,
  historia01SmJpgImg,
  historia01MdWebpImg,
  historia01LgJpgImg,
  historia01SmWebpImg,
  historia01MdJpgImg,
  historia01LgWebpImg,
  historia02SmJpgImg,
  historia02MdWebpImg,
  historia02LgJpgImg,
  historia02SmWebpImg,
  historia02MdJpgImg,
  historia02LgWebpImg,
  historia03SmJpgImg,
  historia03MdWebpImg,
  historia03LgJpgImg,
  historia03SmWebpImg,
  historia03MdJpgImg,
  historia03LgWebpImg,
  historia04SmJpgImg,
  historia04MdWebpImg,
  historia04LgJpgImg,
  historia04SmWebpImg,
  historia04MdJpgImg,
  historia04LgWebpImg,
  historia05SmJpgImg,
  historia05MdWebpImg,
  historia05LgJpgImg,
  historia05SmWebpImg,
  historia05MdJpgImg,
  historia05LgWebpImg,
  historia06SmJpgImg,
  historia06MdWebpImg,
  historia06LgJpgImg,
  historia06SmWebpImg,
  historia06MdJpgImg,
  historia06LgWebpImg,
  historia07SmJpgImg,
  historia07MdWebpImg,
  historia07LgJpgImg,
  historia07SmWebpImg,
  historia07MdJpgImg,
  historia07LgWebpImg,
  finca01SmJpgImg,
  finca01SmWebpImg,
  finca01MdJpgImg,
  finca01MdWebpImg,
  finca01LgJpgImg,
  finca01LgWebpImg,
  finca02SmJpgImg,
  finca02SmWebpImg,
  finca02MdJpgImg,
  finca02MdWebpImg,
  finca02LgJpgImg,
  finca02LgWebpImg,
  finca03SmJpgImg,
  finca03SmWebpImg,
  finca03MdJpgImg,
  finca03MdWebpImg,
  finca03LgJpgImg,
  finca03LgWebpImg,
  finca04SmJpgImg,
  finca04SmWebpImg,
  finca04MdJpgImg,
  finca04MdWebpImg,
  finca04LgJpgImg,
  finca04LgWebpImg,
  finca05SmJpgImg,
  finca05SmWebpImg,
  finca05MdJpgImg,
  finca05MdWebpImg,
  finca05LgJpgImg,
  finca05LgWebpImg,
  equipoAlejandroImg,
  equipoCelinaImg,
  equipoJonyImg,
  equipoSebasImg,
  equipoDiegoImg,
  placeholderAlejandroImg,
  placeholderCelinaImg,
  placeholderJonyImg,
  placeholderSebasImg,
  placeholderDiegoImg,
} from "../utils";

export const mobileNavItems = [
  {
    title: "mobileNav1",
    to: "/vinos",
  },
  {
    title: "mobileNav2",
    to: "/nuestra-historia",
  },
  {
    title: "mobileNav3",
    to: "/la-finca",
  },
  {
    title: "mobileNav4",
    to: "/equipo",
  },
  {
    title: "mobileNav5",
    to: "/donde-comprar",
  },
  {
    title: "mobileNav6",
    to: "/faq",
  },
  {
    title: "mobileNav7",
    to: "/contacto",
  },
];

export const desktopNavItems = [
  {
    title: "desktopNav1",
    to: "/vinos",
  },
  {
    title: "desktopNav2",
    to: "/nuestra-historia",
  },
  {
    title: "desktopNav3",
    to: "/la-finca",
  },
  {
    title: "desktopNav4",
    to: "/equipo",
  },
];

export const bottomNavItems = [
  { to: "/contacto", title: "bottomNav1" },
  { to: "/donde-comprar", title: "bottomNav2" },
  { to: "/faq", title: "bottomNav3" },
];

export const homeImages = [
  {
    imgSmJpg: home01SmJpgImg,
    imgSmAvif: home01SmAvifImg,
    imgMdJpg: home01MdJpgImg,
    imgMdAvif: home01MdAvifImg,
    imgLgJpg: home01LgJpgImg,
    imgLgAvif: home01LgAvifImg,
    imgXlJpg: home01XlJpgImg,
    imgXlAvif: home01XlAvifImg,
    altText: "altText1",
  },
  {
    imgSmJpg: home02SmJpgImg,
    imgSmAvif: home02SmAvifImg,
    imgMdJpg: home02MdJpgImg,
    imgMdAvif: home02MdAvifImg,
    imgLgJpg: home02LgJpgImg,
    imgLgAvif: home02LgAvifImg,
    imgXlJpg: home02XlJpgImg,
    imgXlAvif: home02XlAvifImg,
    altText: "altText2",
  },
  {
    imgSmJpg: home03SmJpgImg,
    imgSmAvif: home03SmAvifImg,
    imgMdJpg: home03MdJpgImg,
    imgMdAvif: home03MdAvifImg,
    imgLgJpg: home03LgJpgImg,
    imgLgAvif: home03LgAvifImg,
    imgXlJpg: home03XlJpgImg,
    imgXlAvif: home03XlAvifImg,
    altText: "altText3",
  },
  {
    imgSmJpg: home04SmJpgImg,
    imgSmAvif: home04SmAvifImg,
    imgMdJpg: home04MdJpgImg,
    imgMdAvif: home04MdAvifImg,
    imgLgJpg: home04LgJpgImg,
    imgLgAvif: home04LgAvifImg,
    imgXlJpg: home04XlJpgImg,
    imgXlAvif: home04XlAvifImg,
    altText: "altText4",
  },
  {
    imgSmJpg: home05SmJpgImg,
    imgSmAvif: home05SmAvifImg,
    imgMdJpg: home05MdJpgImg,
    imgMdAvif: home05MdAvifImg,
    imgLgJpg: home05LgJpgImg,
    imgLgAvif: home05LgAvifImg,
    imgXlJpg: home05XlJpgImg,
    imgXlAvif: home05XlAvifImg,
    altText: "altText5",
  },
  {
    imgSmJpg: home06SmJpgImg,
    imgSmAvif: home06SmAvifImg,
    imgMdJpg: home06MdJpgImg,
    imgMdAvif: home06MdAvifImg,
    imgLgJpg: home06LgJpgImg,
    imgLgAvif: home06LgAvifImg,
    imgXlJpg: home06XlJpgImg,
    imgXlAvif: home06XlAvifImg,
    altText: "altText6",
  },
  {
    imgSmJpg: home07SmJpgImg,
    imgSmAvif: home07SmAvifImg,
    imgMdJpg: home07MdJpgImg,
    imgMdAvif: home07MdAvifImg,
    imgLgJpg: home07LgJpgImg,
    imgLgAvif: home07LgAvifImg,
    imgXlJpg: home07XlJpgImg,
    imgXlAvif: home07XlAvifImg,
    altText: "altText7",
  },
  {
    imgSmJpg: home08SmJpgImg,
    imgSmAvif: home08SmAvifImg,
    imgMdJpg: home08MdJpgImg,
    imgMdAvif: home08MdAvifImg,
    imgLgJpg: home08LgJpgImg,
    imgLgAvif: home08LgAvifImg,
    imgXlJpg: home08XlJpgImg,
    imgXlAvif: home08XlAvifImg,
    altText: "altText8",
  },
];

export const vinos = [
  {
    id: 1,
    filter: "2024",
    type: "type1",
    title: "Pielihueso Naranjo",
    details: "details1",
    detailsCont: "details1Cont",
    imgSmPng: vinosNaranjoSmPngImg,
    imgReverseSmPng: vinosNaranjoContraSmPngImg,
    imgSmAvif: vinosNaranjoSmAvifImg,
    imgReverseSmAvif: vinosNaranjoContraSmAvifImg,
    imgMdPng: vinosNaranjoMdPngImg,
    imgReverseMdPng: vinosNaranjoContraMdPngImg,
    imgMdAvif: vinosNaranjoMdAvifImg,
    imgReverseMdAvif: vinosNaranjoContraMdAvifImg,
    imgLgPng: vinosNaranjoLgPngImg,
    imgReverseLgPng: vinosNaranjoContraLgPngImg,
    imgLgAvif: vinosNaranjoLgAvifImg,
    imgReverseLgAvif: vinosNaranjoContraLgAvifImg,
    imgXlPng: vinosNaranjoXlPngImg,
    imgReverseXlPng: vinosNaranjoContraXlPngImg,
    imgXlAvif: vinosNaranjoXlAvifImg,
    imgReverseXlAvif: vinosNaranjoContraXlAvifImg,
  },
  {
    id: 2,
    filter: "2024",
    type: "type2",
    title: "Tinto de Los Sauces",
    details: "details2",
    detailsCont: "details2Cont",
    imgSmPng: vinosSaucesSmPngImg,
    imgReverseSmPng: vinosSaucesContraSmPngImg,
    imgSmAvif: vinosSaucesSmAvifImg,
    imgReverseSmAvif: vinosSaucesContraSmAvifImg,
    imgMdPng: vinosSaucesMdPngImg,
    imgReverseMdPng: vinosSaucesContraMdPngImg,
    imgMdAvif: vinosSaucesMdAvifImg,
    imgReverseMdAvif: vinosSaucesContraMdAvifImg,
    imgLgPng: vinosSaucesLgPngImg,
    imgReverseLgPng: vinosSaucesContraLgPngImg,
    imgLgAvif: vinosSaucesLgAvifImg,
    imgReverseLgAvif: vinosSaucesContraLgAvifImg,
    imgXlPng: vinosSaucesXlPngImg,
    imgReverseXlPng: vinosSaucesContraXlPngImg,
    imgXlAvif: vinosSaucesXlAvifImg,
    imgReverseXlAvif: vinosSaucesContraXlAvifImg,
  },
  {
    id: 3,
    filter: "2024",
    type: "type3",
    title: "Pielihueso Naranjo Ánfora",
    details: "details3",
    detailsCont: "details3Cont",
    imgSmPng: vinosAnforaSmPngImg,
    imgReverseSmPng: vinosAnforaContraSmPngImg,
    imgSmAvif: vinosAnforaSmAvifImg,
    imgReverseSmAvif: vinosAnforaContraSmAvifImg,
    imgMdPng: vinosAnforaMdPngImg,
    imgReverseMdPng: vinosAnforaContraMdPngImg,
    imgMdAvif: vinosAnforaMdAvifImg,
    imgReverseMdAvif: vinosAnforaContraMdAvifImg,
    imgLgPng: vinosAnforaLgPngImg,
    imgReverseLgPng: vinosAnforaContraLgPngImg,
    imgLgAvif: vinosAnforaLgAvifImg,
    imgReverseLgAvif: vinosAnforaContraLgAvifImg,
    imgXlPng: vinosAnforaXlPngImg,
    imgReverseXlPng: vinosAnforaContraXlPngImg,
    imgXlAvif: vinosAnforaXlAvifImg,
    imgReverseXlAvif: vinosAnforaContraXlAvifImg,
  },
  {
    id: 4,
    filter: "2024",
    type: "type4",
    title: "Pielihueso Rosado Primero",
    details: "details4",
    detailsCont: "details4Cont",
    imgSmPng: vinosRosadoSmPngImg,
    imgReverseSmPng: vinosRosadoContraSmPngImg,
    imgSmAvif: vinosRosadoSmAvifImg,
    imgReverseSmAvif: vinosRosadoContraSmAvifImg,
    imgMdPng: vinosRosadoMdPngImg,
    imgReverseMdPng: vinosRosadoContraMdPngImg,
    imgMdAvif: vinosRosadoMdAvifImg,
    imgReverseMdAvif: vinosRosadoContraMdAvifImg,
    imgLgPng: vinosRosadoLgPngImg,
    imgReverseLgPng: vinosRosadoContraLgPngImg,
    imgLgAvif: vinosRosadoLgAvifImg,
    imgReverseLgAvif: vinosRosadoContraLgAvifImg,
    imgXlPng: vinosRosadoXlPngImg,
    imgReverseXlPng: vinosRosadoContraXlPngImg,
    imgXlAvif: vinosRosadoXlAvifImg,
    imgReverseXlAvif: vinosRosadoContraXlAvifImg,
  },
  {
    id: 5,
    filter: "2024",
    type: "type5",
    title: "Pielihueso Blanco",
    details: "details5",
    detailsCont: "details5Cont",
    imgSmPng: vinosBlancoSmPngImg,
    imgReverseSmPng: vinosBlancoContraSmPngImg,
    imgSmAvif: vinosBlancoSmAvifImg,
    imgReverseSmAvif: vinosBlancoContraSmAvifImg,
    imgMdPng: vinosBlancoMdPngImg,
    imgReverseMdPng: vinosBlancoContraMdPngImg,
    imgMdAvif: vinosBlancoMdAvifImg,
    imgReverseMdAvif: vinosBlancoContraMdAvifImg,
    imgLgPng: vinosBlancoLgPngImg,
    imgReverseLgPng: vinosBlancoContraLgPngImg,
    imgLgAvif: vinosBlancoLgAvifImg,
    imgReverseLgAvif: vinosBlancoContraLgAvifImg,
    imgXlPng: vinosBlancoXlPngImg,
    imgReverseXlPng: vinosBlancoContraXlPngImg,
    imgXlAvif: vinosBlancoXlAvifImg,
    imgReverseXlAvif: vinosBlancoContraXlAvifImg,
  },
  {
    id: 6,
    filter: "2024",
    type: "type6",
    title: "Tinto Villa Seca",
    details: "details6",
    detailsCont: "details6Cont",
    imgSmPng: vinosVillaSmPngImg,
    imgReverseSmPng: vinosVillaContraSmPngImg,
    imgSmAvif: vinosVillaSmAvifImg,
    imgReverseSmAvif: vinosVillaContraSmAvifImg,
    imgMdPng: vinosVillaMdPngImg,
    imgReverseMdPng: vinosVillaContraMdPngImg,
    imgMdAvif: vinosVillaMdAvifImg,
    imgReverseMdAvif: vinosVillaContraMdAvifImg,
    imgLgPng: vinosVillaLgPngImg,
    imgReverseLgPng: vinosVillaContraLgPngImg,
    imgLgAvif: vinosVillaLgAvifImg,
    imgReverseLgAvif: vinosVillaContraLgAvifImg,
    imgXlPng: vinosVillaXlPngImg,
    imgReverseXlPng: vinosVillaContraXlPngImg,
    imgXlAvif: vinosVillaXlAvifImg,
    imgReverseXlAvif: vinosVillaContraXlAvifImg,
  },
  {
    id: 7,
    filter: "Archive",
    type: "type7",
    title: "Malbec Primero",
    details: "details7",
    detailsCont: "details7Cont",
    imgSmPng: vinosMalbecSmPngImg,
    imgReverseSmPng: vinosMalbecContraSmPngImg,
    imgSmAvif: vinosMalbecSmAvifImg,
    imgReverseSmAvif: vinosMalbecContraSmAvifImg,
    imgMdPng: vinosMalbecMdPngImg,
    imgReverseMdPng: vinosMalbecContraMdPngImg,
    imgMdAvif: vinosMalbecMdAvifImg,
    imgReverseMdAvif: vinosMalbecContraMdAvifImg,
    imgLgPng: vinosMalbecLgPngImg,
    imgReverseLgPng: vinosMalbecContraLgPngImg,
    imgLgAvif: vinosMalbecLgAvifImg,
    imgReverseLgAvif: vinosMalbecContraLgAvifImg,
    imgXlPng: vinosMalbecXlPngImg,
    imgReverseXlPng: vinosMalbecContraXlPngImg,
    imgXlAvif: vinosMalbecXlAvifImg,
    imgReverseXlAvif: vinosMalbecContraXlAvifImg,
  },
  {
    id: 8,
    filter: "Archive",
    type: "type8",
    title: "Vino de Señor",
    details: "details8",
    detailsCont: "details8Cont",
    imgSmPng: vinosSenorSmPngImg,
    imgReverseSmPng: vinosSenorContraSmPngImg,
    imgSmAvif: vinosSenorSmAvifImg,
    imgReverseSmAvif: vinosSenorContraSmAvifImg,
    imgMdPng: vinosSenorMdPngImg,
    imgReverseMdPng: vinosSenorContraMdPngImg,
    imgMdAvif: vinosSenorMdAvifImg,
    imgReverseMdAvif: vinosSenorContraMdAvifImg,
    imgLgPng: vinosSenorLgPngImg,
    imgReverseLgPng: vinosSenorContraLgPngImg,
    imgLgAvif: vinosSenorLgAvifImg,
    imgReverseLgAvif: vinosSenorContraLgAvifImg,
    imgXlPng: vinosSenorXlPngImg,
    imgReverseXlPng: vinosSenorContraXlPngImg,
    imgXlAvif: vinosSenorXlAvifImg,
    imgReverseXlAvif: vinosSenorContraXlAvifImg,
  },
  {
    id: 9,
    filter: "Archive",
    type: "type9",
    title: "El Gallo Clara",
    details: "details9",
    detailsCont: "details9Cont",
    imgSmPng: vinosGalloSmPngImg,
    imgReverseSmPng: vinosGalloContraSmPngImg,
    imgSmAvif: vinosGalloSmAvifImg,
    imgReverseSmAvif: vinosGalloContraSmAvifImg,
    imgMdPng: vinosGalloMdPngImg,
    imgReverseMdPng: vinosGalloContraMdPngImg,
    imgMdAvif: vinosGalloMdAvifImg,
    imgReverseMdAvif: vinosGalloContraMdAvifImg,
    imgLgPng: vinosGalloLgPngImg,
    imgReverseLgPng: vinosGalloContraLgPngImg,
    imgLgAvif: vinosGalloLgAvifImg,
    imgReverseLgAvif: vinosGalloContraLgAvifImg,
    imgXlPng: vinosGalloXlPngImg,
    imgReverseXlPng: vinosGalloContraXlPngImg,
    imgXlAvif: vinosGalloXlAvifImg,
    imgReverseXlAvif: vinosGalloContraXlAvifImg,
  },
  {
    id: 10,
    filter: "Archive",
    type: "type10",
    title: "Pintó Verdot",
    details: "details10",
    detailsCont: "details10Cont",
    imgSmPng: vinosPintoSmPngImg,
    imgReverseSmPng: vinosPintoContraSmPngImg,
    imgSmAvif: vinosPintoSmAvifImg,
    imgReverseSmAvif: vinosPintoContraSmAvifImg,
    imgMdPng: vinosPintoMdPngImg,
    imgReverseMdPng: vinosPintoContraMdPngImg,
    imgMdAvif: vinosPintoMdAvifImg,
    imgReverseMdAvif: vinosPintoContraMdAvifImg,
    imgLgPng: vinosPintoLgPngImg,
    imgReverseLgPng: vinosPintoContraLgPngImg,
    imgLgAvif: vinosPintoLgAvifImg,
    imgReverseLgAvif: vinosPintoContraLgAvifImg,
    imgXlPng: vinosPintoXlPngImg,
    imgReverseXlPng: vinosPintoContraXlPngImg,
    imgXlAvif: vinosPintoXlAvifImg,
    imgReverseXlAvif: vinosPintoContraXlAvifImg,
  },
];

export const historyItems = [
  {
    year: "2017",
    text: "text2017",
  },
  {
    year: "2018",
    text: "text2018",
  },
  {
    year: "2019",
    text: "text2019",
  },
  {
    year: "2020",
    text: "text2020",
  },
  {
    year: "2021",
    text: "text2021",
  },
  {
    year: "2022",
    text: "text2022",
  },
  {
    year: "2023",
    text: "text2023",
  },
  {
    year: "2024",
    text: "text2024",
  },
];

export const slidesNuestraHistoria = [
  {
    id: 1,
    imgSmJpg: historia01SmJpgImg,
    imgSmWebp: historia01SmWebpImg,
    imgMdJpg: historia01MdJpgImg,
    imgMdWebp: historia01MdWebpImg,
    imgLgJpg: historia01LgJpgImg,
    imgLgWebp: historia01LgWebpImg,
    altText: "altTextImg1",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg1",
  },
  {
    id: 2,
    imgSmJpg: historia02SmJpgImg,
    imgSmWebp: historia02SmWebpImg,
    imgMdJpg: historia02MdJpgImg,
    imgMdWebp: historia02MdWebpImg,
    imgLgJpg: historia02LgJpgImg,
    imgLgWebp: historia02LgWebpImg,
    altText: "altTextImg2",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg2",
  },
  {
    id: 3,
    imgSmJpg: historia03SmJpgImg,
    imgSmWebp: historia03SmWebpImg,
    imgMdJpg: historia03MdJpgImg,
    imgMdWebp: historia03MdWebpImg,
    imgLgJpg: historia03LgJpgImg,
    imgLgWebp: historia03LgWebpImg,
    altText: "altTextImg3",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg3",
  },
  {
    id: 4,
    imgSmJpg: historia04SmJpgImg,
    imgSmWebp: historia04SmWebpImg,
    imgMdJpg: historia04MdJpgImg,
    imgMdWebp: historia04MdWebpImg,
    imgLgJpg: historia04LgJpgImg,
    imgLgWebp: historia04LgWebpImg,
    altText: "altTextImg4",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg4",
  },
  {
    id: 5,
    imgSmJpg: historia05SmJpgImg,
    imgSmWebp: historia05SmWebpImg,
    imgMdJpg: historia05MdJpgImg,
    imgMdWebp: historia05MdWebpImg,
    imgLgJpg: historia05LgJpgImg,
    imgLgWebp: historia05LgWebpImg,
    altText: "altTextImg5",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg5",
  },
  {
    id: 6,
    imgSmJpg: historia06SmJpgImg,
    imgSmWebp: historia06SmWebpImg,
    imgMdJpg: historia06MdJpgImg,
    imgMdWebp: historia06MdWebpImg,
    imgLgJpg: historia06LgJpgImg,
    imgLgWebp: historia06LgWebpImg,
    altText: "altTextImg6",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg6",
  },
  {
    id: 7,
    imgSmJpg: historia07SmJpgImg,
    imgSmWebp: historia07SmWebpImg,
    imgMdJpg: historia07MdJpgImg,
    imgMdWebp: historia07MdWebpImg,
    imgLgJpg: historia07LgJpgImg,
    imgLgWebp: historia07LgWebpImg,
    altText: "altTextImg7",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg7",
  },
];

export const fincaItems = [
  {
    id: 1,
    attribute: "attribute1",
    detail: "detail1",
  },
  {
    id: 2,
    attribute: "attribute2",
    detail: "detail2",
  },
  {
    id: 3,
    attribute: "attribute3",
    detail: "detail3",
  },
  {
    id: 4,
    attribute: "attribute4",
    detail: "detail4",
  },
  {
    id: 5,
    attribute: "attribute5",
    detail: "detail5",
  },
];

export const slidesLaFinca = [
  {
    id: 1,
    imgSmJpg: finca01SmJpgImg,
    imgSmWebp: finca01SmWebpImg,
    imgMdJpg: finca01MdJpgImg,
    imgMdWebp: finca01MdWebpImg,
    imgLgJpg: finca01LgJpgImg,
    imgLgWebp: finca01LgWebpImg,
    altText: "altTextImg1",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg1",
  },
  {
    id: 2,
    imgSmJpg: finca02SmJpgImg,
    imgSmWebp: finca02SmWebpImg,
    imgMdJpg: finca02MdJpgImg,
    imgMdWebp: finca02MdWebpImg,
    imgLgJpg: finca02LgJpgImg,
    imgLgWebp: finca02LgWebpImg,
    altText: "altTextImg2",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg2",
  },
  {
    id: 3,
    imgSmJpg: finca03SmJpgImg,
    imgSmWebp: finca03SmWebpImg,
    imgMdJpg: finca03MdJpgImg,
    imgMdWebp: finca03MdWebpImg,
    imgLgJpg: finca03LgJpgImg,
    imgLgWebp: finca03LgWebpImg,
    altText: "altTextImg3",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg3",
  },
  {
    id: 4,
    imgSmJpg: finca04SmJpgImg,
    imgSmWebp: finca04SmWebpImg,
    imgMdJpg: finca04MdJpgImg,
    imgMdWebp: finca04MdWebpImg,
    imgLgJpg: finca04LgJpgImg,
    imgLgWebp: finca04LgWebpImg,
    altText: "altTextImg4",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg4",
  },
  {
    id: 5,
    imgSmJpg: finca05SmJpgImg,
    imgSmWebp: finca05SmWebpImg,
    imgMdJpg: finca05MdJpgImg,
    imgMdWebp: finca05MdWebpImg,
    imgLgJpg: finca05LgJpgImg,
    imgLgWebp: finca05LgWebpImg,
    altText: "altTextImg5",
    useSrcSet: true,
    doubleCaption: false,
    caption: "captionImg5",
  },
];

export const slidesEquipo = [
  {
    id: 1,
    img: equipoAlejandroImg,
    placeholder: placeholderAlejandroImg,
    altText: "altTextAlejandro",
    useSrcSet: false,
    doubleCaption: true,
    caption: "Alejandro",
    caption2: "jobAlejandro",
  },
  {
    id: 2,
    img: equipoCelinaImg,
    placeholder: placeholderCelinaImg,
    altText: "altTextCelina",
    useSrcSet: false,
    doubleCaption: true,
    caption: "Celina",
    caption2: "jobCelina",
  },
  {
    id: 3,
    img: equipoJonyImg,
    placeholder: placeholderJonyImg,
    altText: "altTextJony",
    useSrcSet: false,
    doubleCaption: true,
    caption: "Jony",
    caption2: "jobJony",
  },
  {
    id: 4,
    img: equipoSebasImg,
    placeholder: placeholderSebasImg,
    altText: "altTextSebas",
    useSrcSet: false,
    doubleCaption: true,
    caption: "Sebas",
    caption2: "jobSebas",
  },
  {
    id: 5,
    img: equipoDiegoImg,
    placeholder: placeholderDiegoImg,
    altText: "altTextDiego",
    useSrcSet: false,
    doubleCaption: true,
    caption: "Diego",
    caption2: "jobDiego",
  },
];

// export const slidesEquipo = [
//   {
//     id: 1,
//     img: equipoAlejandroImg,
//     altText:
//       "Pielihueso owner Alejandro, smiling in front of a wooden building.",
//     useSrcSet: false,
//     doubleCaption: true,
//     caption: "Alejandro",
//     caption2: "owner",
//   },
//   {
//     id: 2,
//     img: equipoCelinaImg,
//     altText:
//       "Pielihueso owner Celina, holding two bottles of Pielihueso wine in the vineyard.",
//     useSrcSet: false,
//     doubleCaption: true,
//     caption: "Celina",
//     caption2: "owner",
//   },
//   {
//     id: 3,
//     img: equipoJonyImg,
//     altText:
//       "Pielihueso vineyard supervisor Jony, smiling while sitting on a tractor in the vineyard.",
//     useSrcSet: false,
//     doubleCaption: true,
//     caption: "Jony",
//     caption2: "vineyard supervisor",
//   },
//   {
//     id: 4,
//     img: equipoSebasImg,
//     altText:
//       "Pielihueso wine consultant Sebas, sampling wine from a barrel using a wine thief.",
//     useSrcSet: false,
//     doubleCaption: true,
//     caption: "Sebas",
//     caption2: "wine consultant",
//   },
//   {
//     id: 5,
//     img: equipoDiegoImg,
//     altText:
//       "Pielihueso winery assistant Diego, cleaning equipment outside at a winery.",
//     useSrcSet: false,
//     doubleCaption: true,
//     caption: "Diego",
//     caption2: "winery assistant",
//   },
// ];

export const importerItems = [
  {
    id: 1,
    country: "location1",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
  {
    id: 2,
    country: "location2",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
  {
    id: 3,
    country: "location3",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
  {
    id: 4,
    country: "location4",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
  {
    id: 5,
    country: "location5",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
  {
    id: 6,
    country: "location6",
    company: "Brazos Wine Imports",
    website: "www.brazoswine.com",
    address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
    instagram: "https://www.instagram.com/brazoswine",
  },
];

// export const importerItems = [
//   {
//     id: 1,
//     country: "Argentina",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
//   {
//     id: 2,
//     country: "USA",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
//   {
//     id: 3,
//     country: "Spain",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
//   {
//     id: 4,
//     country: "Canada",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
//   {
//     id: 5,
//     country: "Peru",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
//   {
//     id: 6,
//     country: "Japan",
//     company: "Brazos Wine Imports",
//     website: "http://www.brazoswine.com",
//     address: "2 Prince St Suite 4309, Brooklyn, NY 11201, United States",
//     instagram: "https://www.instagram.com/brazoswine",
//   },
// ];

// export const faqItems = [
//   {
//     id: 1,
//     question: "Dónde queda la Bodega?",
//     answer:
//       "Nuestra bodega se encuentra en el corazón del Valle de Uco, Mendoza, Argentina. Estamos ubicados en el Paraje El Cepillo, a 15 kilómetros de Tupungato.",
//   },
//   {
//     id: 2,
//     question: "Aceptan visitas?",
//     answer:
//       "Sí, aceptamos visitas con cita previa. Puede reservar su visita llamando al [número de teléfono] o enviando un correo electrónico a [correo electrónico].",
//   },
//   {
//     id: 3,
//     question: "Cómo compro Pielihueso?",
//     answer:
//       "Puede comprar nuestros vinos en línea a través de nuestro sitio web https://www.brazoswine.com/winery/pielihueso o en una de nuestras tiendas asociadas. También puede encontrar nuestros vinos en algunos restaurantes y bares selectos.",
//   },
//   {
//     id: 4,
//     question: "Cómo hago para vender Pielihueso en mi local?",
//     answer:
//       "Si está interesado en vender Pielihueso en su local, comuníquese con nosotros a través de nuestra página web o por correo electrónico a [correo electrónico].",
//   },
//   {
//     id: 5,
//     question: "Sus vinos tienen sulfitos?",
//     answer:
//       "Sí, nuestros vinos contienen una pequeña cantidad de sulfitos, que se agregan naturalmente durante la fermentación o se agregan en pequeñas cantidades para estabilizar el vino y evitar su deterioro. Sin embargo, nos esforzamos por mantener los niveles de sulfitos lo más bajos posible, utilizando métodos de vinificación tradicionales y minimizando la intervención.",
//   },
//   {
//     id: 6,
//     question: "Mi vino tiene cosas raras, esta malo?",
//     answer:
//       "Si su vino Pielihueso tiene un sabor o aroma inusual, es posible que se haya estropeado. Esto puede suceder por diversas razones, como exposición al calor, luz solar o aire. Si tiene dudas sobre la calidad de su vino, comuníquese con nosotros y estaremos encantados de ayudarlo.",
//   },
// ];

export const faqItems = [
  {
    id: 1,
    question: "question1",
    answer: "answer1",
  },
  {
    id: 21,
    question: "question2",
    answer: "answer2",
  },
  {
    id: 3,
    question: "question3",
    answer: "answer3",
  },
  {
    id: 4,
    question: "question4",
    answer: "answer4",
  },
  {
    id: 5,
    question: "question5",
    answer: "answer5",
  },
  {
    id: 6,
    question: "question6",
    answer: "answer6",
  },
];
