import logo from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Logo.svg";
import iconInstagram from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-IGicon.svg";
import iconSmiley from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Smiley.png";
import iconSmileyWink from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Smiley-Wink.png";

// here

import home01SmJpg from "../assets/images/Home/home-01-sm.jpg";
import home01SmAvif from "../assets/images/Home/home-01-sm.avif";
import home01MdJpg from "../assets/images/Home/home-01-md.jpg";
import home01MdAvif from "../assets/images/Home/home-01-md.avif";
import home01LgJpg from "../assets/images/Home/home-01-lg.jpg";
import home01LgAvif from "../assets/images/Home/home-01-lg.avif";
import home01XlJpg from "../assets/images/Home/home-01-xl.jpg";
import home01XlAvif from "../assets/images/Home/home-01-xl.avif";
import home02SmJpg from "../assets/images/Home/home-02-sm.jpg";
import home02SmAvif from "../assets/images/Home/home-02-sm.avif";
import home02MdJpg from "../assets/images/Home/home-02-md.jpg";
import home02MdAvif from "../assets/images/Home/home-02-md.avif";
import home02LgJpg from "../assets/images/Home/home-02-lg.jpg";
import home02LgAvif from "../assets/images/Home/home-02-lg.avif";
import home02XlJpg from "../assets/images/Home/home-02-xl.jpg";
import home02XlAvif from "../assets/images/Home/home-02-xl.avif";
import home03SmJpg from "../assets/images/Home/home-03-sm.jpg";
import home03SmAvif from "../assets/images/Home/home-03-sm.avif";
import home03MdJpg from "../assets/images/Home/home-03-md.jpg";
import home03MdAvif from "../assets/images/Home/home-03-md.avif";
import home03LgJpg from "../assets/images/Home/home-03-lg.jpg";
import home03LgAvif from "../assets/images/Home/home-03-lg.avif";
import home03XlJpg from "../assets/images/Home/home-03-xl.jpg";
import home03XlAvif from "../assets/images/Home/home-03-xl.avif";
import home04SmJpg from "../assets/images/Home/home-04-sm.jpg";
import home04SmAvif from "../assets/images/Home/home-04-sm.avif";
import home04MdJpg from "../assets/images/Home/home-04-md.jpg";
import home04MdAvif from "../assets/images/Home/home-04-md.avif";
import home04LgJpg from "../assets/images/Home/home-04-lg.jpg";
import home04LgAvif from "../assets/images/Home/home-04-lg.avif";
import home04XlJpg from "../assets/images/Home/home-04-xl.jpg";
import home04XlAvif from "../assets/images/Home/home-04-xl.avif";
import home05SmJpg from "../assets/images/Home/home-05-sm.jpg";
import home05SmAvif from "../assets/images/Home/home-05-sm.avif";
import home05MdJpg from "../assets/images/Home/home-05-md.jpg";
import home05MdAvif from "../assets/images/Home/home-05-md.avif";
import home05LgJpg from "../assets/images/Home/home-05-lg.jpg";
import home05LgAvif from "../assets/images/Home/home-05-lg.avif";
import home05XlJpg from "../assets/images/Home/home-05-xl.jpg";
import home05XlAvif from "../assets/images/Home/home-05-xl.avif";
import home06SmJpg from "../assets/images/Home/home-06-sm.jpg";
import home06SmAvif from "../assets/images/Home/home-06-sm.avif";
import home06MdJpg from "../assets/images/Home/home-06-md.jpg";
import home06MdAvif from "../assets/images/Home/home-06-md.avif";
import home06LgJpg from "../assets/images/Home/home-06-lg.jpg";
import home06LgAvif from "../assets/images/Home/home-06-lg.avif";
import home06XlJpg from "../assets/images/Home/home-06-xl.jpg";
import home06XlAvif from "../assets/images/Home/home-06-xl.avif";
import home07SmJpg from "../assets/images/Home/home-07-sm.jpg";
import home07SmAvif from "../assets/images/Home/home-07-sm.avif";
import home07MdJpg from "../assets/images/Home/home-07-md.jpg";
import home07MdAvif from "../assets/images/Home/home-07-md.avif";
import home07LgJpg from "../assets/images/Home/home-07-lg.jpg";
import home07LgAvif from "../assets/images/Home/home-07-lg.avif";
import home07XlJpg from "../assets/images/Home/home-07-xl.jpg";
import home07XlAvif from "../assets/images/Home/home-07-xl.avif";

// import home1JpegSm from "../assets/images/Home/test2/pielihueso-home-5-sm.jpg";
// import home1AvifSm from "../assets/images/Home/test2/pielihueso-home-5-sm.webp";
// import home1JpegMd from "../assets/images/Home/test2/pielihueso-home-5-md.jpg";
// import home1AvifMd from "../assets/images/Home/test2/pielihueso-home-5-md.webp";
// import home1JpegLg from "../assets/images/Home/test2/pielihueso-home-5-lg.jpg";
// import home1AvifLg from "../assets/images/Home/test2/pielihueso-home-5-lg.webp";
// import home1JpegXl from "../assets/images/Home/test2/pielihueso-home-5-xl.jpg";
// import home1AvifXl from "../assets/images/Home/test2/pielihueso-home-5-xl.webp";

// import home1JpegSm from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-sm.jpg";
// import home1AvifSm from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-sm.avif";
// import home1AvifMd from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-md.avif";
// import home1JpegMd from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-md.jpg";
// import home1AvifLg from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-lg.avif";
// import home1JpegLg from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-lg.jpg";
// import home1AvifXl from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-xl.avif";
// import home1JpegXl from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-xl.jpg";
// import home1AvifXxl from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-xxl.avif";
// import home1JpegXxl from "../assets/images/Home/test/05.2024-WebPielihueso-Img-Home-1-xxl.jpg";

import homeMobile1 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-1.jpg";
import homeMobile2 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-2.jpg";
import homeMobile3 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-3.jpg";
import homeMobile4 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-4.jpg";
import homeMobile5 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-5.jpg";
import homeMobile6 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-6.jpg";
import homeMobile7 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-7.jpg";
import homeMobile8 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Mobile-8.jpg";
import homeTablet1 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-1.jpg";
import homeTablet2 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-2.jpg";
import homeTablet3 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-3.jpg";
import homeTablet4 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-4.jpg";
import homeTablet5 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-5.jpg";
import homeTablet6 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-6.jpg";
import homeTablet7 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-7.jpg";
import homeTablet8 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Tablet-8.jpg";
import homeDesktop1 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-1.jpg";
import homeDesktop2 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-2.jpg";
import homeDesktop3 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-3.jpg";
import homeDesktop4 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-4.jpg";
import homeDesktop5 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-5.jpg";
import homeDesktop6 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-6.jpg";
import homeDesktop7 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-7.jpg";
import homeDesktop8 from "../assets/images/Home/04.2024-WebPielihueso-Img-Home-Desktop-8.jpg";

import naranjoFrontSm from "../assets/images/Vinos/vinos-naranjo-front-sm.webp";
import naranjoFrontMd from "../assets/images/Vinos/vinos-naranjo-front-md.webp";
import naranjoFrontLg from "../assets/images/Vinos/vinos-naranjo-front-lg.webp";
import naranjoFrontXl from "../assets/images/Vinos/vinos-naranjo-front-xl.webp";
import naranjoBackSm from "../assets/images/Vinos/vinos-naranjo-back-sm.webp";
import naranjoBackMd from "../assets/images/Vinos/vinos-naranjo-back-md.webp";
import naranjoBackLg from "../assets/images/Vinos/vinos-naranjo-back-lg.webp";
import naranjoBackXl from "../assets/images/Vinos/vinos-naranjo-back-xl.webp";
// import naranjoMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Narnjo.png";
// import naranjoTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Narnjo-Tablet.png";
// import naranjoDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Narnjo-Desktop.png";
import losSaucesMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-LosSauces.png";
import losSaucesTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-LosSauces-Tablet.png";
import losSaucesDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-LosSauces-Desktop.png";
import naranjoAnforaMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora.png";
import naranjoAnforaTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora-Tablet.png";
import naranjoAnforaDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora-Desktop.png";
import rosadoPrimeroMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero.png";
import rosadoPrimeroTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero-Tablet.png";
import rosadoPrimeroDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero-Desktop.png";
import blancoMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Blanco.png";
import blancoTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Blanco-Tablet.png";
import blancoDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-Blanco-Desktop.png";
import villaSecaMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-VillaSeca.png";
import villaSecaTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-VillaSeca-Tablet.png";
import villaSecaDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-VillaSeca-Desktop.png";
import malbecPrimeroMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero.png";
import malbecPrimeroTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero-Tablet.png";
import malbecPrimeroDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero-Desktop.png";
import vinoDeSenorMobile from "../assets/images/Vinos/vinos-vino-de-senor-sm.webp";
import vinoDeSenorTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-VinoDeSenor-Tablet.png";
import vinoDeSenorDesktop from "../assets/images/Vinos/vinos-vino-de-senor-lg.webp";
import galloClaraMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-GalloClara.png";
import galloClaraTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-GalloClara-Tablet.png";
import galloClaraDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-GalloClara-Desktop.png";
import pintoVerdotMobile from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-PintoVerdot.png";
import pintoVerdotTablet from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-PintoVerdot-Tablet.png";
import pintoVerdotDesktop from "../assets/images/Vinos/04.2024-WebPielihueso-Img-Vinos-PintoVerdot-Desktop.png";

import historiaMainSmJpg from "../assets/images/Nuestra Historia/historia-main-sm.jpg";
import historiaMainSmWebp from "../assets/images/Nuestra Historia/historia-main-sm.webp";
import historiaMainMdJpg from "../assets/images/Nuestra Historia/historia-main-md.jpg";
import historiaMainMdWebp from "../assets/images/Nuestra Historia/historia-main-md.webp";
import historiaMainLgJpg from "../assets/images/Nuestra Historia/historia-main-lg.jpg";
import historiaMainLgWebp from "../assets/images/Nuestra Historia/historia-main-lg.webp";
import historiaMainXlJpg from "../assets/images/Nuestra Historia/historia-main-xl.jpg";
import historiaMainXlWebp from "../assets/images/Nuestra Historia/historia-main-xl.webp";
import historiaMainXxlJpg from "../assets/images/Nuestra Historia/historia-main-xxl.jpg";
import historiaMainXxlWebp from "../assets/images/Nuestra Historia/historia-main-xxl.webp";
import historiaMainXxxlJpg from "../assets/images/Nuestra Historia/historia-main-xxxl.jpg";
import historiaMainXxxlWebp from "../assets/images/Nuestra Historia/historia-main-xxxl.webp";

import historiaSecondaryLgPng from "../assets/images/Nuestra Historia/historia-secondary-lg.png";
import historiaSecondaryLgWebp from "../assets/images/Nuestra Historia/historia-secondary-lg.webp";
import historiaSecondaryMdPng from "../assets/images/Nuestra Historia/historia-secondary-md.png";
import historiaSecondaryMdWebp from "../assets/images/Nuestra Historia/historia-secondary-md.webp";

import historia01SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-sm.jpg";
import historia01SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-sm.webp";
import historia01MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-md.jpg";
import historia01MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-md.webp";
import historia01LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-lg.jpg";
import historia01LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-lg.webp";
import historia02SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-sm.jpg";
import historia02SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-sm.webp";
import historia02MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-md.jpg";
import historia02MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-md.webp";
import historia02LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-lg.jpg";
import historia02LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-lg.webp";
import historia03SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-sm.jpg";
import historia03SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-sm.webp";
import historia03MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-md.jpg";
import historia03MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-md.webp";
import historia03LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-lg.jpg";
import historia03LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-lg.webp";
import historia04SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-sm.jpg";
import historia04SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-sm.webp";
import historia04MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-md.jpg";
import historia04MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-md.webp";
import historia04LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-lg.jpg";
import historia04LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-lg.webp";
import historia05SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-sm.jpg";
import historia05SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-sm.webp";
import historia05MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-md.jpg";
import historia05MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-md.webp";
import historia05LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-lg.jpg";
import historia05LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-lg.webp";
import historia06SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-sm.jpg";
import historia06SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-sm.webp";
import historia06MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-md.jpg";
import historia06MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-md.webp";
import historia06LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-lg.jpg";
import historia06LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-lg.webp";
import historia07SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-sm.jpg";
import historia07SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-sm.webp";
import historia07MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-md.jpg";
import historia07MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-md.webp";
import historia07LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-lg.jpg";
import historia07LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-lg.webp";

import historiaMobile1 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-1.jpg";
import historiaMobile2 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-2.jpg";
import historiaMobile3 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-3.jpg";
import historiaMobile4 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-4.jpg";
import historiaMobile5 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-5.jpg";
import historiaMobile6 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-6.jpg";
import historiaMobile7 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-7.jpg";
import historiaDesktop1 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-1.jpg";
import historiaDesktop2 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-2.jpg";
import historiaDesktop3 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-3.jpg";
import historiaDesktop4 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-4.jpg";
import historiaDesktop5 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-5.jpg";
import historiaDesktop6 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-6.jpg";
import historiaDesktop7 from "../assets/images/Nuestra Historia/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-7.jpg";

import fincaMainSmJpg from "../assets/images/La Finca/la-finca-main-sm.jpg";
import fincaMainSmWebp from "../assets/images/La Finca/la-finca-main-sm.webp";
import fincaMainMdJpg from "../assets/images/La Finca/la-finca-main-md.jpg";
import fincaMainMdWebp from "../assets/images/La Finca/la-finca-main-md.webp";
import fincaMainLgJpg from "../assets/images/La Finca/la-finca-main-lg.jpg";
import fincaMainLgWebp from "../assets/images/La Finca/la-finca-main-lg.webp";
import finca01SmJpg from "../assets/images/La Finca/la-finca-01-sm.jpg";
import finca01SmWebp from "../assets/images/La Finca/la-finca-01-sm.webp";
import finca01MdJpg from "../assets/images/La Finca/la-finca-01-md.jpg";
import finca01MdWebp from "../assets/images/La Finca/la-finca-01-md.webp";
import finca01LgJpg from "../assets/images/La Finca/la-finca-01-lg.jpg";
import finca01LgWebp from "../assets/images/La Finca/la-finca-01-lg.webp";
import finca02SmJpg from "../assets/images/La Finca/la-finca-02-sm.jpg";
import finca02SmWebp from "../assets/images/La Finca/la-finca-02-sm.webp";
import finca02MdJpg from "../assets/images/La Finca/la-finca-02-md.jpg";
import finca02MdWebp from "../assets/images/La Finca/la-finca-02-md.webp";
import finca02LgJpg from "../assets/images/La Finca/la-finca-02-lg.jpg";
import finca02LgWebp from "../assets/images/La Finca/la-finca-02-lg.webp";
import finca03SmJpg from "../assets/images/La Finca/la-finca-03-sm.jpg";
import finca03SmWebp from "../assets/images/La Finca/la-finca-03-sm.webp";
import finca03MdJpg from "../assets/images/La Finca/la-finca-03-md.jpg";
import finca03MdWebp from "../assets/images/La Finca/la-finca-03-md.webp";
import finca03LgJpg from "../assets/images/La Finca/la-finca-03-lg.jpg";
import finca03LgWebp from "../assets/images/La Finca/la-finca-03-lg.webp";
import finca04SmJpg from "../assets/images/La Finca/la-finca-04-sm.jpg";
import finca04SmWebp from "../assets/images/La Finca/la-finca-04-sm.webp";
import finca04MdJpg from "../assets/images/La Finca/la-finca-04-md.jpg";
import finca04MdWebp from "../assets/images/La Finca/la-finca-04-md.webp";
import finca04LgJpg from "../assets/images/La Finca/la-finca-04-lg.jpg";
import finca04LgWebp from "../assets/images/La Finca/la-finca-04-lg.webp";
import finca05SmJpg from "../assets/images/La Finca/la-finca-05-sm.jpg";
import finca05SmWebp from "../assets/images/La Finca/la-finca-05-sm.webp";
import finca05MdJpg from "../assets/images/La Finca/la-finca-05-md.jpg";
import finca05MdWebp from "../assets/images/La Finca/la-finca-05-md.webp";
import finca05LgJpg from "../assets/images/La Finca/la-finca-05-lg.jpg";
import finca05LgWebp from "../assets/images/La Finca/la-finca-05-lg.webp";

import equipoAlejandro from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Alejandro-Desktop.webp";
import equipoCelina from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Celina-Desktop.webp";
import equipoJony from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Jony-Desktop.webp";
import equipoSebas from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Sebas-Desktop.webp";
import equipoDiego from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Diego-Desktop.webp";
import placeholderAlejandro from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Alejandro-Desktop-ezgif.com-crop.jpg";
import placeholderCelina from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Celina-Desktop-ezgif.com-crop.jpg";
import placeholderJony from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Jony-Desktop-ezgif.com-crop.jpg";
import placeholderSebas from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Sebas-Desktop-ezgif.com-crop.jpg";
import placeholderDiego from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Diego-Desktop-ezgif.com-crop.jpg";

import contactoSmPng from "../assets/images/Contacto/contacto-sm.png";
import contactoSmWebp from "../assets/images/Contacto/contacto-sm.webp";
import contactoMdPng from "../assets/images/Contacto/contacto-md.png";
import contactoMdWebp from "../assets/images/Contacto/contacto-md.webp";
import contactoLgPng from "../assets/images/Contacto/contacto-lg.png";
import contactoLgWebp from "../assets/images/Contacto/contacto-lg.webp";
import contactoXlPng from "../assets/images/Contacto/contacto-xl.png";
import contactoXlWebp from "../assets/images/Contacto/contacto-xl.webp";

import comprarSmPng from "../assets/images/Donde Comprar/donde-comprar-sm.png";
import comprarSmWebp from "../assets/images/Donde Comprar/donde-comprar-sm.webp";
import comprarMdPng from "../assets/images/Donde Comprar/donde-comprar-md.png";
import comprarMdWebp from "../assets/images/Donde Comprar/donde-comprar-md.webp";
import comprarLgPng from "../assets/images/Donde Comprar/donde-comprar-lg.png";
import comprarLgWebp from "../assets/images/Donde Comprar/donde-comprar-lg.webp";
import comprarXlPng from "../assets/images/Donde Comprar/donde-comprar-xl.png";
import comprarXlWebp from "../assets/images/Donde Comprar/donde-comprar-xl.webp";

import faqSmPng from "../assets/images/FAQ/faq-sm.png";
import faqSmWebp from "../assets/images/FAQ/faq-sm.webp";
import faqMdPng from "../assets/images/FAQ/faq-md.png";
import faqMdWebp from "../assets/images/FAQ/faq-md.webp";
import faqLgPng from "../assets/images/FAQ/faq-lg.png";
import faqLgWebp from "../assets/images/FAQ/faq-lg.webp";
import faqXlPng from "../assets/images/FAQ/faq-xl.png";
import faqXlWebp from "../assets/images/FAQ/faq-xl.webp";

import iconExpand from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-expand.svg";
import iconClose from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-close.svg";
import iconArrowRight from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-arrow-right.svg";
import iconArrowLeft from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-arrow-left.svg";

export const logoImg = logo;
export const iconInstagramImg = iconInstagram;
export const iconSmileyImg = iconSmiley;
export const iconSmileyWinkImg = iconSmileyWink;

export const home01SmJpgImg = home01SmJpg;
export const home01SmAvifImg = home01SmAvif;
export const home01MdJpgImg = home01MdJpg;
export const home01MdAvifImg = home01MdAvif;
export const home01LgJpgImg = home01LgJpg;
export const home01LgAvifImg = home01LgAvif;
export const home01XlJpgImg = home01XlJpg;
export const home01XlAvifImg = home01XlAvif;
export const home02SmJpgImg = home02SmJpg;
export const home02SmAvifImg = home02SmAvif;
export const home02MdJpgImg = home02MdJpg;
export const home02MdAvifImg = home02MdAvif;
export const home02LgJpgImg = home02LgJpg;
export const home02LgAvifImg = home02LgAvif;
export const home02XlJpgImg = home02XlJpg;
export const home02XlAvifImg = home02XlAvif;
export const home03SmJpgImg = home03SmJpg;
export const home03SmAvifImg = home03SmAvif;
export const home03MdJpgImg = home03MdJpg;
export const home03MdAvifImg = home03MdAvif;
export const home03LgJpgImg = home03LgJpg;
export const home03LgAvifImg = home03LgAvif;
export const home03XlJpgImg = home03XlJpg;
export const home03XlAvifImg = home03XlAvif;
export const home04SmJpgImg = home04SmJpg;
export const home04SmAvifImg = home04SmAvif;
export const home04MdJpgImg = home04MdJpg;
export const home04MdAvifImg = home04MdAvif;
export const home04LgJpgImg = home04LgJpg;
export const home04LgAvifImg = home04LgAvif;
export const home04XlJpgImg = home04XlJpg;
export const home04XlAvifImg = home04XlAvif;
export const home05SmJpgImg = home05SmJpg;
export const home05SmAvifImg = home05SmAvif;
export const home05MdJpgImg = home05MdJpg;
export const home05MdAvifImg = home05MdAvif;
export const home05LgJpgImg = home05LgJpg;
export const home05LgAvifImg = home05LgAvif;
export const home05XlJpgImg = home05XlJpg;
export const home05XlAvifImg = home05XlAvif;
export const home06SmJpgImg = home06SmJpg;
export const home06SmAvifImg = home06SmAvif;
export const home06MdJpgImg = home06MdJpg;
export const home06MdAvifImg = home06MdAvif;
export const home06LgJpgImg = home06LgJpg;
export const home06LgAvifImg = home06LgAvif;
export const home06XlJpgImg = home06XlJpg;
export const home06XlAvifImg = home06XlAvif;
export const home07SmJpgImg = home07SmJpg;
export const home07SmAvifImg = home07SmAvif;
export const home07MdJpgImg = home07MdJpg;
export const home07MdAvifImg = home07MdAvif;
export const home07LgJpgImg = home07LgJpg;
export const home07LgAvifImg = home07LgAvif;
export const home07XlJpgImg = home07XlJpg;
export const home07XlAvifImg = home07XlAvif;

// export const home1JpegSmImg = home1JpegSm;
// export const home1AvifSmImg = home1AvifSm;
// export const home1JpegMdImg = home1JpegMd;
// export const home1AvifMdImg = home1AvifMd;
// export const home1JpegLgImg = home1JpegLg;
// export const home1AvifLgImg = home1AvifLg;
// export const home1JpegXlImg = home1JpegXl;
// export const home1AvifXlImg = home1AvifXl;
// export const home1JpegXxlImg = home1JpegXxl;
// export const home1AvifXxlImg = home1AvifXxl;

// export const homeMobile1Img = homeMobile1;
// export const homeMobile2Img = homeMobile2;
// export const homeMobile3Img = homeMobile3;
// export const homeMobile4Img = homeMobile4;
// export const homeMobile5Img = homeMobile5;
// export const homeMobile6Img = homeMobile6;
// export const homeMobile7Img = homeMobile7;
// export const homeMobile8Img = homeMobile8;
// export const homeTablet1Img = homeTablet1;
// export const homeTablet2Img = homeTablet2;
// export const homeTablet3Img = homeTablet3;
// export const homeTablet4Img = homeTablet4;
// export const homeTablet5Img = homeTablet5;
// export const homeTablet6Img = homeTablet6;
// export const homeTablet7Img = homeTablet7;
// export const homeTablet8Img = homeTablet8;
// export const homeDesktop1Img = homeDesktop1;
// export const homeDesktop2Img = homeDesktop2;
// export const homeDesktop3Img = homeDesktop3;
// export const homeDesktop4Img = homeDesktop4;
// export const homeDesktop5Img = homeDesktop5;
// export const homeDesktop6Img = homeDesktop6;
// export const homeDesktop7Img = homeDesktop7;
// export const homeDesktop8Img = homeDesktop8;

export const naranjoFrontSmImg = naranjoFrontSm;
export const naranjoFrontMdImg = naranjoFrontMd;
export const naranjoFrontLgImg = naranjoFrontLg;
export const naranjoFrontXlImg = naranjoFrontXl;
export const naranjoBackSmImg = naranjoBackSm;
export const naranjoBackMdImg = naranjoBackMd;
export const naranjoBackLgImg = naranjoBackLg;
export const naranjoBackXlImg = naranjoBackXl;
// export const naranjoMobileImg = naranjoMobile;
// export const naranjoTabletImg = naranjoTablet;
// export const naranjoDesktopImg = naranjoDesktop;
export const losSaucesMobileImg = losSaucesMobile;
export const losSaucesTabletImg = losSaucesTablet;
export const losSaucesDesktopImg = losSaucesDesktop;
export const naranjoAnforaMobileImg = naranjoAnforaMobile;
export const naranjoAnforaTabletImg = naranjoAnforaTablet;
export const naranjoAnforaDesktopImg = naranjoAnforaDesktop;
export const rosadoPrimeroMobileImg = rosadoPrimeroMobile;
export const rosadoPrimeroTabletImg = rosadoPrimeroTablet;
export const rosadoPrimeroDesktopImg = rosadoPrimeroDesktop;
export const blancoMobileImg = blancoMobile;
export const blancoTabletImg = blancoTablet;
export const blancoDesktopImg = blancoDesktop;
export const villaSecaMobileImg = villaSecaMobile;
export const villaSecaTabletImg = villaSecaTablet;
export const villaSecaDesktopImg = villaSecaDesktop;
export const malbecPrimeroMobileImg = malbecPrimeroMobile;
export const malbecPrimeroTabletImg = malbecPrimeroTablet;
export const malbecPrimeroDesktopImg = malbecPrimeroDesktop;
export const vinoDeSenorMobileImg = vinoDeSenorMobile;
export const vinoDeSenorTabletImg = vinoDeSenorTablet;
export const vinoDeSenorDesktopImg = vinoDeSenorDesktop;
export const galloClaraMobileImg = galloClaraMobile;
export const galloClaraTabletImg = galloClaraTablet;
export const galloClaraDesktopImg = galloClaraDesktop;
export const pintoVerdotMobileImg = pintoVerdotMobile;
export const pintoVerdotTabletImg = pintoVerdotTablet;
export const pintoVerdotDesktopImg = pintoVerdotDesktop;

export const historiaMainSmJpgImg = historiaMainSmJpg;
export const historiaMainSmWebpImg = historiaMainSmWebp;
export const historiaMainMdJpgImg = historiaMainMdJpg;
export const historiaMainMdWebpImg = historiaMainMdWebp;
export const historiaMainLgJpgImg = historiaMainLgJpg;
export const historiaMainLgWebpImg = historiaMainLgWebp;
export const historiaMainXlJpgImg = historiaMainXlJpg;
export const historiaMainXlWebpImg = historiaMainXlWebp;
export const historiaMainXxlJpgImg = historiaMainXxlJpg;
export const historiaMainXxlWebpImg = historiaMainXxlWebp;
export const historiaMainXxxlJpgImg = historiaMainXxxlJpg;
export const historiaMainXxxlWebpImg = historiaMainXxxlWebp;

export const historia01SmJpgImg = historia01SmJpg;
export const historia01MdWebpImg = historia01MdWebp;
export const historia01LgJpgImg = historia01LgJpg;
export const historia01SmWebpImg = historia01SmWebp;
export const historia01MdJpgImg = historia01MdJpg;
export const historia01LgWebpImg = historia01LgWebp;
export const historia02SmJpgImg = historia02SmJpg;
export const historia02MdWebpImg = historia02MdWebp;
export const historia02LgJpgImg = historia02LgJpg;
export const historia02SmWebpImg = historia02SmWebp;
export const historia02MdJpgImg = historia02MdJpg;
export const historia02LgWebpImg = historia02LgWebp;
export const historia03SmJpgImg = historia03SmJpg;
export const historia03MdWebpImg = historia03MdWebp;
export const historia03LgJpgImg = historia03LgJpg;
export const historia03SmWebpImg = historia03SmWebp;
export const historia03MdJpgImg = historia03MdJpg;
export const historia03LgWebpImg = historia03LgWebp;
export const historia04SmJpgImg = historia04SmJpg;
export const historia04MdWebpImg = historia04MdWebp;
export const historia04LgJpgImg = historia04LgJpg;
export const historia04SmWebpImg = historia04SmWebp;
export const historia04MdJpgImg = historia04MdJpg;
export const historia04LgWebpImg = historia04LgWebp;
export const historia05SmJpgImg = historia05SmJpg;
export const historia05MdWebpImg = historia05MdWebp;
export const historia05LgJpgImg = historia05LgJpg;
export const historia05SmWebpImg = historia05SmWebp;
export const historia05MdJpgImg = historia05MdJpg;
export const historia05LgWebpImg = historia05LgWebp;
export const historia06SmJpgImg = historia06SmJpg;
export const historia06MdWebpImg = historia06MdWebp;
export const historia06LgJpgImg = historia06LgJpg;
export const historia06SmWebpImg = historia06SmWebp;
export const historia06MdJpgImg = historia06MdJpg;
export const historia06LgWebpImg = historia06LgWebp;
export const historia07SmJpgImg = historia07SmJpg;
export const historia07MdWebpImg = historia07MdWebp;
export const historia07LgJpgImg = historia07LgJpg;
export const historia07SmWebpImg = historia07SmWebp;
export const historia07MdJpgImg = historia07MdJpg;
export const historia07LgWebpImg = historia07LgWebp;

export const historiaSecondaryMdPngImg = historiaSecondaryMdPng;
export const historiaSecondaryMdWebpImg = historiaSecondaryMdWebp;
export const historiaSecondaryLgPngImg = historiaSecondaryLgPng;
export const historiaSecondaryLgWebpImg = historiaSecondaryLgWebp;

export const historiaMobile1Img = historiaMobile1;
export const historiaMobile2Img = historiaMobile2;
export const historiaMobile3Img = historiaMobile3;
export const historiaMobile4Img = historiaMobile4;
export const historiaMobile5Img = historiaMobile5;
export const historiaMobile6Img = historiaMobile6;
export const historiaMobile7Img = historiaMobile7;
export const historiaDesktop1Img = historiaDesktop1;
export const historiaDesktop2Img = historiaDesktop2;
export const historiaDesktop3Img = historiaDesktop3;
export const historiaDesktop4Img = historiaDesktop4;
export const historiaDesktop5Img = historiaDesktop5;
export const historiaDesktop6Img = historiaDesktop6;
export const historiaDesktop7Img = historiaDesktop7;

export const fincaMainSmJpgImg = fincaMainSmJpg;
export const fincaMainSmWebpImg = fincaMainSmWebp;
export const fincaMainMdJpgImg = fincaMainMdJpg;
export const fincaMainMdWebpImg = fincaMainMdWebp;
export const fincaMainLgJpgImg = fincaMainLgJpg;
export const fincaMainLgWebpImg = fincaMainLgWebp;
export const finca01SmJpgImg = finca01SmJpg;
export const finca01SmWebpImg = finca01SmWebp;
export const finca01MdJpgImg = finca01MdJpg;
export const finca01MdWebpImg = finca01MdWebp;
export const finca01LgJpgImg = finca01LgJpg;
export const finca01LgWebpImg = finca01LgWebp;
export const finca02SmJpgImg = finca02SmJpg;
export const finca02SmWebpImg = finca02SmWebp;
export const finca02MdJpgImg = finca02MdJpg;
export const finca02MdWebpImg = finca02MdWebp;
export const finca02LgJpgImg = finca02LgJpg;
export const finca02LgWebpImg = finca02LgWebp;
export const finca03SmJpgImg = finca03SmJpg;
export const finca03SmWebpImg = finca03SmWebp;
export const finca03MdJpgImg = finca03MdJpg;
export const finca03MdWebpImg = finca03MdWebp;
export const finca03LgJpgImg = finca03LgJpg;
export const finca03LgWebpImg = finca03LgWebp;
export const finca04SmJpgImg = finca04SmJpg;
export const finca04SmWebpImg = finca04SmWebp;
export const finca04MdJpgImg = finca04MdJpg;
export const finca04MdWebpImg = finca04MdWebp;
export const finca04LgJpgImg = finca04LgJpg;
export const finca04LgWebpImg = finca04LgWebp;
export const finca05SmJpgImg = finca05SmJpg;
export const finca05SmWebpImg = finca05SmWebp;
export const finca05MdJpgImg = finca05MdJpg;
export const finca05MdWebpImg = finca05MdWebp;
export const finca05LgJpgImg = finca05LgJpg;
export const finca05LgWebpImg = finca05LgWebp;

export const equipoAlejandroImg = equipoAlejandro;
export const equipoCelinaImg = equipoCelina;
export const equipoJonyImg = equipoJony;
export const equipoSebasImg = equipoSebas;
export const equipoDiegoImg = equipoDiego;
export const placeholderAlejandroImg = placeholderAlejandro;
export const placeholderCelinaImg = placeholderCelina;
export const placeholderJonyImg = placeholderJony;
export const placeholderSebasImg = placeholderSebas;
export const placeholderDiegoImg = placeholderDiego;

export const contactoSmPngImg = contactoSmPng;
export const contactoSmWebpImg = contactoSmWebp;
export const contactoMdPngImg = contactoMdPng;
export const contactoMdWebpImg = contactoMdWebp;
export const contactoLgPngImg = contactoLgPng;
export const contactoLgWebpImg = contactoLgWebp;
export const contactoXlPngImg = contactoXlPng;
export const contactoXlWebpImg = contactoXlWebp;

export const comprarSmPngImg = comprarSmPng;
export const comprarSmWebpImg = comprarSmWebp;
export const comprarMdPngImg = comprarMdPng;
export const comprarMdWebpImg = comprarMdWebp;
export const comprarLgPngImg = comprarLgPng;
export const comprarLgWebpImg = comprarLgWebp;
export const comprarXlPngImg = comprarXlPng;
export const comprarXlWebpImg = comprarXlWebp;

export const faqSmPngImg = faqSmPng;
export const faqSmWebpImg = faqSmWebp;
export const faqMdPngImg = faqMdPng;
export const faqMdWebpImg = faqMdWebp;
export const faqLgPngImg = faqLgPng;
export const faqLgWebpImg = faqLgWebp;
export const faqXlPngImg = faqXlPng;
export const faqXlWebpImg = faqXlWebp;

export const iconExpandImg = iconExpand;
export const iconCloseImg = iconClose;
export const iconArrowRightImg = iconArrowRight;
export const iconArrowLeftImg = iconArrowLeft;
