import homeMobile1 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-1.jpg";
import homeMobile2 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-2.jpg";
import homeMobile3 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-3.jpg";
import homeMobile4 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-4.jpg";
import homeMobile5 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-5.jpg";
import homeMobile6 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-6.jpg";
import homeMobile7 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-7.jpg";
import homeMobile8 from "/assets/04.2024-WebPielihueso-Img-Home-Mobile-8.jpg";
import homeTablet1 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-1.jpg";
import homeTablet2 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-2.jpg";
import homeTablet3 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-3.jpg";
import homeTablet4 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-4.jpg";
import homeTablet5 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-5.jpg";
import homeTablet6 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-6.jpg";
import homeTablet7 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-7.jpg";
import homeTablet8 from "/assets/04.2024-WebPielihueso-Img-Home-Tablet-8.jpg";
import homeDesktop1 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-1.jpg";
import homeDesktop2 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-2.jpg";
import homeDesktop3 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-3.jpg";
import homeDesktop4 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-4.jpg";
import homeDesktop5 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-5.jpg";
import homeDesktop6 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-6.jpg";
import homeDesktop7 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-7.jpg";
import homeDesktop8 from "/assets/04.2024-WebPielihueso-Img-Home-Desktop-8.jpg";

import naranjoMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-Narnjo.png";
import naranjoTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-Narnjo-Tablet.png";
import naranjoDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-Narnjo-Desktop.png";
import losSaucesMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-LosSauces.png";
import losSaucesTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-LosSauces-Tablet.png";
import losSaucesDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-LosSauces-Desktop.png";
import naranjoAnforaMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora.png";
import naranjoAnforaTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora-Tablet.png";
import naranjoAnforaDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-NaranjoAnfora-Desktop.png";
import rosadoPrimeroMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero.png";
import rosadoPrimeroTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero-Tablet.png";
import rosadoPrimeroDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-RosadoPrimero-Desktop.png";
import blancoMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-Blanco.png";
import blancoTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-Blanco-Tablet.png";
import blancoDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-Blanco-Desktop.png";
import villaSecaMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-VillaSeca.png";
import villaSecaTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-VillaSeca-Tablet.png";
import villaSecaDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-VillaSeca-Desktop.png";
import malbecPrimeroMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero.png";
import malbecPrimeroTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero-Tablet.png";
import malbecPrimeroDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-MalbecPrimero-Desktop.png";
import vinoDeSenorMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-VinoDeSenor.png";
import vinoDeSenorTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-VinoDeSenor-Tablet.png";
import vinoDeSenorDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-VinoDeSenor-Desktop.png";
import galloClaraMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-GalloClara.png";
import galloClaraTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-GalloClara-Tablet.png";
import galloClaraDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-GalloClara-Desktop.png";
import pintoVerdotMobile from "/assets/04.2024-WebPielihueso-Img-Vinos-PintoVerdot.png";
import pintoVerdotTablet from "/assets/04.2024-WebPielihueso-Img-Vinos-PintoVerdot-Tablet.png";
import pintoVerdotDesktop from "/assets/04.2024-WebPielihueso-Img-Vinos-PintoVerdot-Desktop.png";

import historiaPrimaryMobile from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-01-Mobile.jpg";
import historiaPrimaryTablet from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-01-Tablet.jpg";
import historiaPrimaryDesktop from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-01-Desktop.jpg";
import historiaSecondaryMobile from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-02-Mobile.png";
import historiaSecondaryDesktop from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-02-Desktop.png";
import historiaMobile1 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-1.jpg";
import historiaMobile2 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-2.jpg";
import historiaMobile3 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-3.jpg";
import historiaMobile4 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-4.jpg";
import historiaMobile5 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-5.jpg";
import historiaMobile6 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-6.jpg";
import historiaMobile7 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Mobile-7.jpg";
import historiaDesktop1 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-1.jpg";
import historiaDesktop2 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-2.jpg";
import historiaDesktop3 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-3.jpg";
import historiaDesktop4 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-4.jpg";
import historiaDesktop5 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-5.jpg";
import historiaDesktop6 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-6.jpg";
import historiaDesktop7 from "/assets/04.2024-WebPielihueso-Img-NuestraHistoria-Carrousel-Desktop-7.jpg";

import fincaPrimaryMobile from "/assets/04.2024-WebPielihueso-Img-LaFinca-01-Mobile.jpg";
import fincaPrimaryTablet from "/assets/04.2024-WebPielihueso-Img-LaFinca-01-Tablet.jpg";
import fincaPrimaryDesktop from "/assets/04.2024-WebPielihueso-Img-LaFinca-01-Desktop.jpg";
import fincaMobile1 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Mobile-1.jpg";
import fincaTablet1 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Tablet-1.jpg";
import fincaDesktop1 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Desktop-1.jpg";
import fincaMobile2 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Mobile-2.jpg";
import fincaTablet2 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Tablet-2.jpg";
import fincaDesktop2 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Desktop-2.jpg";
import fincaMobile3 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Mobile-3.jpg";
import fincaTablet3 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Tablet-3.jpg";
import fincaDesktop3 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Desktop-3.jpg";
import fincaMobile4 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Mobile-4.jpg";
import fincaTablet4 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Tablet-4.jpg";
import fincaDesktop4 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Desktop-4.jpg";
import fincaMobile5 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Mobile-5.jpg";
import fincaTablet5 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Tablet-5.jpg";
import fincaDesktop5 from "/assets/04.2024-WebPielihueso-Img-LaFinca-Carrousel-Desktop-5.jpg";

import equipoAlejandro from "/assets/04.2024-WebPielihueso-Img-Equipo-Alejandro-Desktop.webp";
import equipoCelina from "/assets/04.2024-WebPielihueso-Img-Equipo-Celina-Desktop.webp";
import equipoJony from "/assets/04.2024-WebPielihueso-Img-Equipo-Jony-Desktop.webp";
import equipoSebas from "/assets/04.2024-WebPielihueso-Img-Equipo-Sebas-Desktop.webp";
import equipoDiego from "/assets/04.2024-WebPielihueso-Img-Equipo-Diego-Desktop.webp";

import contactoMobilePrimary from "/assets/04.2024-WebPielihueso-Img-Contacto-Mobile.png";
import contactoDesktopPrimary from "/assets/04.2024-WebPielihueso-Img-Contacto-Desktop.png";

import comprarMobilePrimary from "/assets/04.2024-WebPielihueso-Img-DondeComprar-Mobile.png";
import comprarDesktopPrimary from "/assets/04.2024-WebPielihueso-Img-DondeComprar-Desktop.png";

import iconExpand from "/assets/04.2024-WebPielihueso-Img-expand.svg";
import iconClose from "/assets/04.2024-WebPielihueso-Img-close.svg";
import faqMobilePrimary from "/assets/04.2024-WebPielihueso-Img-FAQs-Mobile.png";
import faqTabletPrimary from "/assets/04.2024-WebPielihueso-Img-FAQs-Tablet.png";
import faqDesktopPrimary from "/assets/04.2024-WebPielihueso-Img-FAQs-Desktop.png";

import iconArrowRight from "/assets/04.2024-WebPielihueso-Img-arrow-right.svg";
import iconArrowLeft from "/assets/04.2024-WebPielihueso-Img-arrow-left.svg";
import iconArrowRightCarousel from "/assets/04.2024-WebPielihueso-Img-arrow-right-carousel.svg";
import iconArrowLeftCarousel from "/assets/04.2024-WebPielihueso-Img-arrow-left-carousel.svg";

export const homeMobile1Img = homeMobile1;
export const homeMobile2Img = homeMobile2;
export const homeMobile3Img = homeMobile3;
export const homeMobile4Img = homeMobile4;
export const homeMobile5Img = homeMobile5;
export const homeMobile6Img = homeMobile6;
export const homeMobile7Img = homeMobile7;
export const homeMobile8Img = homeMobile8;
export const homeTablet1Img = homeTablet1;
export const homeTablet2Img = homeTablet2;
export const homeTablet3Img = homeTablet3;
export const homeTablet4Img = homeTablet4;
export const homeTablet5Img = homeTablet5;
export const homeTablet6Img = homeTablet6;
export const homeTablet7Img = homeTablet7;
export const homeTablet8Img = homeTablet8;
export const homeDesktop1Img = homeDesktop1;
export const homeDesktop2Img = homeDesktop2;
export const homeDesktop3Img = homeDesktop3;
export const homeDesktop4Img = homeDesktop4;
export const homeDesktop5Img = homeDesktop5;
export const homeDesktop6Img = homeDesktop6;
export const homeDesktop7Img = homeDesktop7;
export const homeDesktop8Img = homeDesktop8;

export const naranjoMobileImg = naranjoMobile;
export const naranjoTabletImg = naranjoTablet;
export const naranjoDesktopImg = naranjoDesktop;
export const losSaucesMobileImg = losSaucesMobile;
export const losSaucesTabletImg = losSaucesTablet;
export const losSaucesDesktopImg = losSaucesDesktop;
export const naranjoAnforaMobileImg = naranjoAnforaMobile;
export const naranjoAnforaTabletImg = naranjoAnforaTablet;
export const naranjoAnforaDesktopImg = naranjoAnforaDesktop;
export const rosadoPrimeroMobileImg = rosadoPrimeroMobile;
export const rosadoPrimeroTabletImg = rosadoPrimeroTablet;
export const rosadoPrimeroDesktopImg = rosadoPrimeroDesktop;
export const blancoMobileImg = blancoMobile;
export const blancoTabletImg = blancoTablet;
export const blancoDesktopImg = blancoDesktop;
export const villaSecaMobileImg = villaSecaMobile;
export const villaSecaTabletImg = villaSecaTablet;
export const villaSecaDesktopImg = villaSecaDesktop;
export const malbecPrimeroMobileImg = malbecPrimeroMobile;
export const malbecPrimeroTabletImg = malbecPrimeroTablet;
export const malbecPrimeroDesktopImg = malbecPrimeroDesktop;
export const vinoDeSenorMobileImg = vinoDeSenorMobile;
export const vinoDeSenorTabletImg = vinoDeSenorTablet;
export const vinoDeSenorDesktopImg = vinoDeSenorDesktop;
export const galloClaraMobileImg = galloClaraMobile;
export const galloClaraTabletImg = galloClaraTablet;
export const galloClaraDesktopImg = galloClaraDesktop;
export const pintoVerdotMobileImg = pintoVerdotMobile;
export const pintoVerdotTabletImg = pintoVerdotTablet;
export const pintoVerdotDesktopImg = pintoVerdotDesktop;

export const historiaPrimaryMobileImg = historiaPrimaryMobile;
export const historiaPrimaryTabletImg = historiaPrimaryTablet;
export const historiaPrimaryDesktopImg = historiaPrimaryDesktop;
export const historiaSecondaryMobileImg = historiaSecondaryMobile;
export const historiaSecondaryDesktopImg = historiaSecondaryDesktop;
export const historiaMobile1Img = historiaMobile1;
export const historiaMobile2Img = historiaMobile2;
export const historiaMobile3Img = historiaMobile3;
export const historiaMobile4Img = historiaMobile4;
export const historiaMobile5Img = historiaMobile5;
export const historiaMobile6Img = historiaMobile6;
export const historiaMobile7Img = historiaMobile7;
export const historiaDesktop1Img = historiaDesktop1;
export const historiaDesktop2Img = historiaDesktop2;
export const historiaDesktop3Img = historiaDesktop3;
export const historiaDesktop4Img = historiaDesktop4;
export const historiaDesktop5Img = historiaDesktop5;
export const historiaDesktop6Img = historiaDesktop6;
export const historiaDesktop7Img = historiaDesktop7;

export const fincaPrimaryMobileImg = fincaPrimaryMobile;
export const fincaPrimaryTabletImg = fincaPrimaryTablet;
export const fincaPrimaryDesktopImg = fincaPrimaryDesktop;
export const fincaMobile1Img = fincaMobile1;
export const fincaTablet1Img = fincaTablet1;
export const fincaDesktop1Img = fincaDesktop1;
export const fincaMobile2Img = fincaMobile2;
export const fincaTablet2Img = fincaTablet2;
export const fincaDesktop2Img = fincaDesktop2;
export const fincaMobile3Img = fincaMobile3;
export const fincaTablet3Img = fincaTablet3;
export const fincaDesktop3Img = fincaDesktop3;
export const fincaMobile4Img = fincaMobile4;
export const fincaTablet4Img = fincaTablet4;
export const fincaDesktop4Img = fincaDesktop4;
export const fincaMobile5Img = fincaMobile5;
export const fincaTablet5Img = fincaTablet5;
export const fincaDesktop5Img = fincaDesktop5;

export const equipoAlejandroImg = equipoAlejandro;
export const equipoCelinaImg = equipoCelina;
export const equipoJonyImg = equipoJony;
export const equipoSebasImg = equipoSebas;
export const equipoDiegoImg = equipoDiego;

export const contactoMobilePrimaryImg = contactoMobilePrimary;
export const contactoDesktopPrimaryImg = contactoDesktopPrimary;

export const comprarMobilePrimaryImg = comprarMobilePrimary;
export const comprarDesktopPrimaryImg = comprarDesktopPrimary;

export const iconExpandImg = iconExpand;
export const iconCloseImg = iconClose;
export const faqMobilePrimaryImg = faqMobilePrimary;
export const faqTabletPrimaryImg = faqTabletPrimary;
export const faqDesktopPrimaryImg = faqDesktopPrimary;

export const iconArrowRightImg = iconArrowRight;
export const iconArrowLeftImg = iconArrowLeft;
export const iconArrowRightCarouselImg = iconArrowRightCarousel;
export const iconArrowLeftCarouselImg = iconArrowLeftCarousel;
