import logo from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Logo.svg";
import iconInstagram from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-IGicon.svg";
import iconSmiley from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Smiley.png";
import iconSmileyWink from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-Smiley-Wink.png";

import home01SmJpg from "../assets/images/Home/home-01-sm.jpg";
import home01SmAvif from "../assets/images/Home/home-01-sm.avif";
import home01MdJpg from "../assets/images/Home/home-01-md.jpg";
import home01MdAvif from "../assets/images/Home/home-01-md.avif";
import home01LgJpg from "../assets/images/Home/home-01-lg.jpg";
import home01LgAvif from "../assets/images/Home/home-01-lg.avif";
import home01XlJpg from "../assets/images/Home/home-01-xl.jpg";
import home01XlAvif from "../assets/images/Home/home-01-xl.avif";
import home02SmJpg from "../assets/images/Home/home-02-sm.jpg";
import home02SmAvif from "../assets/images/Home/home-02-sm.avif";
import home02MdJpg from "../assets/images/Home/home-02-md.jpg";
import home02MdAvif from "../assets/images/Home/home-02-md.avif";
import home02LgJpg from "../assets/images/Home/home-02-lg.jpg";
import home02LgAvif from "../assets/images/Home/home-02-lg.avif";
import home02XlJpg from "../assets/images/Home/home-02-xl.jpg";
import home02XlAvif from "../assets/images/Home/home-02-xl.avif";
import home03SmJpg from "../assets/images/Home/home-03-sm.jpg";
import home03SmAvif from "../assets/images/Home/home-03-sm.avif";
import home03MdJpg from "../assets/images/Home/home-03-md.jpg";
import home03MdAvif from "../assets/images/Home/home-03-md.avif";
import home03LgJpg from "../assets/images/Home/home-03-lg.jpg";
import home03LgAvif from "../assets/images/Home/home-03-lg.avif";
import home03XlJpg from "../assets/images/Home/home-03-xl.jpg";
import home03XlAvif from "../assets/images/Home/home-03-xl.avif";
import home04SmJpg from "../assets/images/Home/home-04-sm.jpg";
import home04SmAvif from "../assets/images/Home/home-04-sm.avif";
import home04MdJpg from "../assets/images/Home/home-04-md.jpg";
import home04MdAvif from "../assets/images/Home/home-04-md.avif";
import home04LgJpg from "../assets/images/Home/home-04-lg.jpg";
import home04LgAvif from "../assets/images/Home/home-04-lg.avif";
import home04XlJpg from "../assets/images/Home/home-04-xl.jpg";
import home04XlAvif from "../assets/images/Home/home-04-xl.avif";
import home05SmJpg from "../assets/images/Home/home-05-sm.jpg";
import home05SmAvif from "../assets/images/Home/home-05-sm.avif";
import home05MdJpg from "../assets/images/Home/home-05-md.jpg";
import home05MdAvif from "../assets/images/Home/home-05-md.avif";
import home05LgJpg from "../assets/images/Home/home-05-lg.jpg";
import home05LgAvif from "../assets/images/Home/home-05-lg.avif";
import home05XlJpg from "../assets/images/Home/home-05-xl.jpg";
import home05XlAvif from "../assets/images/Home/home-05-xl.avif";
import home06SmJpg from "../assets/images/Home/home-06-sm.jpg";
import home06SmAvif from "../assets/images/Home/home-06-sm.avif";
import home06MdJpg from "../assets/images/Home/home-06-md.jpg";
import home06MdAvif from "../assets/images/Home/home-06-md.avif";
import home06LgJpg from "../assets/images/Home/home-06-lg.jpg";
import home06LgAvif from "../assets/images/Home/home-06-lg.avif";
import home06XlJpg from "../assets/images/Home/home-06-xl.jpg";
import home06XlAvif from "../assets/images/Home/home-06-xl.avif";
import home07SmJpg from "../assets/images/Home/home-07-sm.jpg";
import home07SmAvif from "../assets/images/Home/home-07-sm.avif";
import home07MdJpg from "../assets/images/Home/home-07-md.jpg";
import home07MdAvif from "../assets/images/Home/home-07-md.avif";
import home07LgJpg from "../assets/images/Home/home-07-lg.jpg";
import home07LgAvif from "../assets/images/Home/home-07-lg.avif";
import home07XlJpg from "../assets/images/Home/home-07-xl.jpg";
import home07XlAvif from "../assets/images/Home/home-07-xl.avif";
import home08SmJpg from "../assets/images/Home/home-08-sm.jpg";
import home08SmAvif from "../assets/images/Home/home-08-sm.avif";
import home08MdJpg from "../assets/images/Home/home-08-md.jpg";
import home08MdAvif from "../assets/images/Home/home-08-md.avif";
import home08LgJpg from "../assets/images/Home/home-08-lg.jpg";
import home08LgAvif from "../assets/images/Home/home-08-lg.avif";
import home08XlJpg from "../assets/images/Home/home-08-xl.jpg";
import home08XlAvif from "../assets/images/Home/home-08-xl.avif";

import vinosAnforaSmPng from "../assets/images/Vinos/vinos-anfora-sm.png";
import vinosAnforaContraSmPng from "../assets/images/Vinos/vinos-anfora-contra-sm.png";
import vinosAnforaSmAvif from "../assets/images/Vinos/vinos-anfora-sm.avif";
import vinosAnforaContraSmAvif from "../assets/images/Vinos/vinos-anfora-contra-sm.avif";
import vinosAnforaMdPng from "../assets/images/Vinos/vinos-anfora-md.png";
import vinosAnforaContraMdPng from "../assets/images/Vinos/vinos-anfora-contra-md.png";
import vinosAnforaMdAvif from "../assets/images/Vinos/vinos-anfora-md.avif";
import vinosAnforaContraMdAvif from "../assets/images/Vinos/vinos-anfora-contra-md.avif";
import vinosAnforaLgPng from "../assets/images/Vinos/vinos-anfora-lg.png";
import vinosAnforaContraLgPng from "../assets/images/Vinos/vinos-anfora-contra-lg.png";
import vinosAnforaLgAvif from "../assets/images/Vinos/vinos-anfora-lg.avif";
import vinosAnforaContraLgAvif from "../assets/images/Vinos/vinos-anfora-contra-lg.avif";
import vinosAnforaXlPng from "../assets/images/Vinos/vinos-anfora-xl.png";
import vinosAnforaContraXlPng from "../assets/images/Vinos/vinos-anfora-contra-xl.png";
import vinosAnforaXlAvif from "../assets/images/Vinos/vinos-anfora-xl.avif";
import vinosAnforaContraXlAvif from "../assets/images/Vinos/vinos-anfora-contra-xl.avif";
import vinosGalloSmPng from "../assets/images/Vinos/vinos-gallo-sm.png";
import vinosGalloContraSmPng from "../assets/images/Vinos/vinos-gallo-contra-sm.png";
import vinosGalloSmAvif from "../assets/images/Vinos/vinos-gallo-sm.avif";
import vinosGalloContraSmAvif from "../assets/images/Vinos/vinos-gallo-contra-sm.avif";
import vinosGalloMdPng from "../assets/images/Vinos/vinos-gallo-md.png";
import vinosGalloContraMdPng from "../assets/images/Vinos/vinos-gallo-contra-md.png";
import vinosGalloMdAvif from "../assets/images/Vinos/vinos-gallo-md.avif";
import vinosGalloContraMdAvif from "../assets/images/Vinos/vinos-gallo-contra-md.avif";
import vinosGalloLgPng from "../assets/images/Vinos/vinos-gallo-lg.png";
import vinosGalloContraLgPng from "../assets/images/Vinos/vinos-gallo-contra-lg.png";
import vinosGalloLgAvif from "../assets/images/Vinos/vinos-gallo-lg.avif";
import vinosGalloContraLgAvif from "../assets/images/Vinos/vinos-gallo-contra-lg.avif";
import vinosGalloXlPng from "../assets/images/Vinos/vinos-gallo-xl.png";
import vinosGalloContraXlPng from "../assets/images/Vinos/vinos-gallo-contra-xl.png";
import vinosGalloXlAvif from "../assets/images/Vinos/vinos-gallo-xl.avif";
import vinosGalloContraXlAvif from "../assets/images/Vinos/vinos-gallo-contra-xl.avif";
import vinosVillaSmPng from "../assets/images/Vinos/vinos-villa-sm.png";
import vinosVillaContraSmPng from "../assets/images/Vinos/vinos-villa-contra-sm.png";
import vinosVillaSmAvif from "../assets/images/Vinos/vinos-villa-sm.avif";
import vinosVillaContraSmAvif from "../assets/images/Vinos/vinos-villa-contra-sm.avif";
import vinosVillaMdPng from "../assets/images/Vinos/vinos-villa-md.png";
import vinosVillaContraMdPng from "../assets/images/Vinos/vinos-villa-contra-md.png";
import vinosVillaMdAvif from "../assets/images/Vinos/vinos-villa-md.avif";
import vinosVillaContraMdAvif from "../assets/images/Vinos/vinos-villa-contra-md.avif";
import vinosVillaLgPng from "../assets/images/Vinos/vinos-villa-lg.png";
import vinosVillaContraLgPng from "../assets/images/Vinos/vinos-villa-contra-lg.png";
import vinosVillaLgAvif from "../assets/images/Vinos/vinos-villa-lg.avif";
import vinosVillaContraLgAvif from "../assets/images/Vinos/vinos-villa-contra-lg.avif";
import vinosVillaXlPng from "../assets/images/Vinos/vinos-villa-xl.png";
import vinosVillaContraXlPng from "../assets/images/Vinos/vinos-villa-contra-xl.png";
import vinosVillaXlAvif from "../assets/images/Vinos/vinos-villa-xl.avif";
import vinosVillaContraXlAvif from "../assets/images/Vinos/vinos-villa-contra-xl.avif";
import vinosPintoSmPng from "../assets/images/Vinos/vinos-pinto-sm.png";
import vinosPintoContraSmPng from "../assets/images/Vinos/vinos-pinto-contra-sm.png";
import vinosPintoSmAvif from "../assets/images/Vinos/vinos-pinto-sm.avif";
import vinosPintoContraSmAvif from "../assets/images/Vinos/vinos-pinto-contra-sm.avif";
import vinosPintoMdPng from "../assets/images/Vinos/vinos-pinto-md.png";
import vinosPintoContraMdPng from "../assets/images/Vinos/vinos-pinto-contra-md.png";
import vinosPintoMdAvif from "../assets/images/Vinos/vinos-pinto-md.avif";
import vinosPintoContraMdAvif from "../assets/images/Vinos/vinos-pinto-contra-md.avif";
import vinosPintoLgPng from "../assets/images/Vinos/vinos-pinto-lg.png";
import vinosPintoContraLgPng from "../assets/images/Vinos/vinos-pinto-contra-lg.png";
import vinosPintoLgAvif from "../assets/images/Vinos/vinos-pinto-lg.avif";
import vinosPintoContraLgAvif from "../assets/images/Vinos/vinos-pinto-contra-lg.avif";
import vinosPintoXlPng from "../assets/images/Vinos/vinos-pinto-xl.png";
import vinosPintoContraXlPng from "../assets/images/Vinos/vinos-pinto-contra-xl.png";
import vinosPintoXlAvif from "../assets/images/Vinos/vinos-pinto-xl.avif";
import vinosPintoContraXlAvif from "../assets/images/Vinos/vinos-pinto-contra-xl.avif";
import vinosNaranjoSmPng from "../assets/images/Vinos/vinos-naranjo-sm.png";
import vinosNaranjoContraSmPng from "../assets/images/Vinos/vinos-naranjo-contra-sm.png";
import vinosNaranjoSmAvif from "../assets/images/Vinos/vinos-naranjo-sm.avif";
import vinosNaranjoContraSmAvif from "../assets/images/Vinos/vinos-naranjo-contra-sm.avif";
import vinosNaranjoMdPng from "../assets/images/Vinos/vinos-naranjo-md.png";
import vinosNaranjoContraMdPng from "../assets/images/Vinos/vinos-naranjo-contra-md.png";
import vinosNaranjoMdAvif from "../assets/images/Vinos/vinos-naranjo-md.avif";
import vinosNaranjoContraMdAvif from "../assets/images/Vinos/vinos-naranjo-contra-md.avif";
import vinosNaranjoLgPng from "../assets/images/Vinos/vinos-naranjo-lg.png";
import vinosNaranjoContraLgPng from "../assets/images/Vinos/vinos-naranjo-contra-lg.png";
import vinosNaranjoLgAvif from "../assets/images/Vinos/vinos-naranjo-lg.avif";
import vinosNaranjoContraLgAvif from "../assets/images/Vinos/vinos-naranjo-contra-lg.avif";
import vinosNaranjoXlPng from "../assets/images/Vinos/vinos-naranjo-xl.png";
import vinosNaranjoContraXlPng from "../assets/images/Vinos/vinos-naranjo-contra-xl.png";
import vinosNaranjoXlAvif from "../assets/images/Vinos/vinos-naranjo-xl.avif";
import vinosNaranjoContraXlAvif from "../assets/images/Vinos/vinos-naranjo-contra-xl.avif";
import vinosMalbecSmPng from "../assets/images/Vinos/vinos-malbec-sm.png";
import vinosMalbecContraSmPng from "../assets/images/Vinos/vinos-malbec-contra-sm.png";
import vinosMalbecSmAvif from "../assets/images/Vinos/vinos-malbec-sm.avif";
import vinosMalbecContraSmAvif from "../assets/images/Vinos/vinos-malbec-contra-sm.avif";
import vinosMalbecMdPng from "../assets/images/Vinos/vinos-malbec-md.png";
import vinosMalbecContraMdPng from "../assets/images/Vinos/vinos-malbec-contra-md.png";
import vinosMalbecMdAvif from "../assets/images/Vinos/vinos-malbec-md.avif";
import vinosMalbecContraMdAvif from "../assets/images/Vinos/vinos-malbec-contra-md.avif";
import vinosMalbecLgPng from "../assets/images/Vinos/vinos-malbec-lg.png";
import vinosMalbecContraLgPng from "../assets/images/Vinos/vinos-malbec-contra-lg.png";
import vinosMalbecLgAvif from "../assets/images/Vinos/vinos-malbec-lg.avif";
import vinosMalbecContraLgAvif from "../assets/images/Vinos/vinos-malbec-contra-lg.avif";
import vinosMalbecXlPng from "../assets/images/Vinos/vinos-malbec-xl.png";
import vinosMalbecContraXlPng from "../assets/images/Vinos/vinos-malbec-contra-xl.png";
import vinosMalbecXlAvif from "../assets/images/Vinos/vinos-malbec-xl.avif";
import vinosMalbecContraXlAvif from "../assets/images/Vinos/vinos-malbec-contra-xl.avif";
import vinosSenorSmPng from "../assets/images/Vinos/vinos-senor-sm.png";
import vinosSenorContraSmPng from "../assets/images/Vinos/vinos-senor-contra-sm.png";
import vinosSenorSmAvif from "../assets/images/Vinos/vinos-senor-sm.avif";
import vinosSenorContraSmAvif from "../assets/images/Vinos/vinos-senor-contra-sm.avif";
import vinosSenorMdPng from "../assets/images/Vinos/vinos-senor-md.png";
import vinosSenorContraMdPng from "../assets/images/Vinos/vinos-senor-contra-md.png";
import vinosSenorMdAvif from "../assets/images/Vinos/vinos-senor-md.avif";
import vinosSenorContraMdAvif from "../assets/images/Vinos/vinos-senor-contra-md.avif";
import vinosSenorLgPng from "../assets/images/Vinos/vinos-senor-lg.png";
import vinosSenorContraLgPng from "../assets/images/Vinos/vinos-senor-contra-lg.png";
import vinosSenorLgAvif from "../assets/images/Vinos/vinos-senor-lg.avif";
import vinosSenorContraLgAvif from "../assets/images/Vinos/vinos-senor-contra-lg.avif";
import vinosSenorXlPng from "../assets/images/Vinos/vinos-senor-xl.png";
import vinosSenorContraXlPng from "../assets/images/Vinos/vinos-senor-contra-xl.png";
import vinosSenorXlAvif from "../assets/images/Vinos/vinos-senor-xl.avif";
import vinosSenorContraXlAvif from "../assets/images/Vinos/vinos-senor-contra-xl.avif";
import vinosRosadoSmPng from "../assets/images/Vinos/vinos-rosado-sm.png";
import vinosRosadoContraSmPng from "../assets/images/Vinos/vinos-rosado-contra-sm.png";
import vinosRosadoSmAvif from "../assets/images/Vinos/vinos-rosado-sm.avif";
import vinosRosadoContraSmAvif from "../assets/images/Vinos/vinos-rosado-contra-sm.avif";
import vinosRosadoMdPng from "../assets/images/Vinos/vinos-rosado-md.png";
import vinosRosadoContraMdPng from "../assets/images/Vinos/vinos-rosado-contra-md.png";
import vinosRosadoMdAvif from "../assets/images/Vinos/vinos-rosado-md.avif";
import vinosRosadoContraMdAvif from "../assets/images/Vinos/vinos-rosado-contra-md.avif";
import vinosRosadoLgPng from "../assets/images/Vinos/vinos-rosado-lg.png";
import vinosRosadoContraLgPng from "../assets/images/Vinos/vinos-rosado-contra-lg.png";
import vinosRosadoLgAvif from "../assets/images/Vinos/vinos-rosado-lg.avif";
import vinosRosadoContraLgAvif from "../assets/images/Vinos/vinos-rosado-contra-lg.avif";
import vinosRosadoXlPng from "../assets/images/Vinos/vinos-rosado-xl.png";
import vinosRosadoContraXlPng from "../assets/images/Vinos/vinos-rosado-contra-xl.png";
import vinosRosadoXlAvif from "../assets/images/Vinos/vinos-rosado-xl.avif";
import vinosRosadoContraXlAvif from "../assets/images/Vinos/vinos-rosado-contra-xl.avif";
import vinosSaucesSmPng from "../assets/images/Vinos/vinos-sauces-sm.png";
import vinosSaucesContraSmPng from "../assets/images/Vinos/vinos-sauces-contra-sm.png";
import vinosSaucesSmAvif from "../assets/images/Vinos/vinos-sauces-sm.avif";
import vinosSaucesContraSmAvif from "../assets/images/Vinos/vinos-sauces-contra-sm.avif";
import vinosSaucesMdPng from "../assets/images/Vinos/vinos-sauces-md.png";
import vinosSaucesContraMdPng from "../assets/images/Vinos/vinos-sauces-contra-md.png";
import vinosSaucesMdAvif from "../assets/images/Vinos/vinos-sauces-md.avif";
import vinosSaucesContraMdAvif from "../assets/images/Vinos/vinos-sauces-contra-md.avif";
import vinosSaucesLgPng from "../assets/images/Vinos/vinos-sauces-lg.png";
import vinosSaucesContraLgPng from "../assets/images/Vinos/vinos-sauces-contra-lg.png";
import vinosSaucesLgAvif from "../assets/images/Vinos/vinos-sauces-lg.avif";
import vinosSaucesContraLgAvif from "../assets/images/Vinos/vinos-sauces-contra-lg.avif";
import vinosSaucesXlPng from "../assets/images/Vinos/vinos-sauces-xl.png";
import vinosSaucesContraXlPng from "../assets/images/Vinos/vinos-sauces-contra-xl.png";
import vinosSaucesXlAvif from "../assets/images/Vinos/vinos-sauces-xl.avif";
import vinosSaucesContraXlAvif from "../assets/images/Vinos/vinos-sauces-contra-xl.avif";
import vinosBlancoSmPng from "../assets/images/Vinos/vinos-blanco-sm.png";
import vinosBlancoContraSmPng from "../assets/images/Vinos/vinos-blanco-contra-sm.png";
import vinosBlancoSmAvif from "../assets/images/Vinos/vinos-blanco-sm.avif";
import vinosBlancoContraSmAvif from "../assets/images/Vinos/vinos-blanco-contra-sm.avif";
import vinosBlancoMdPng from "../assets/images/Vinos/vinos-blanco-md.png";
import vinosBlancoContraMdPng from "../assets/images/Vinos/vinos-blanco-contra-md.png";
import vinosBlancoMdAvif from "../assets/images/Vinos/vinos-blanco-md.avif";
import vinosBlancoContraMdAvif from "../assets/images/Vinos/vinos-blanco-contra-md.avif";
import vinosBlancoLgPng from "../assets/images/Vinos/vinos-blanco-lg.png";
import vinosBlancoContraLgPng from "../assets/images/Vinos/vinos-blanco-contra-lg.png";
import vinosBlancoLgAvif from "../assets/images/Vinos/vinos-blanco-lg.avif";
import vinosBlancoContraLgAvif from "../assets/images/Vinos/vinos-blanco-contra-lg.avif";
import vinosBlancoXlPng from "../assets/images/Vinos/vinos-blanco-xl.png";
import vinosBlancoContraXlPng from "../assets/images/Vinos/vinos-blanco-contra-xl.png";
import vinosBlancoXlAvif from "../assets/images/Vinos/vinos-blanco-xl.avif";
import vinosBlancoContraXlAvif from "../assets/images/Vinos/vinos-blanco-contra-xl.avif";

import historiaMainSmJpg from "../assets/images/Nuestra Historia/historia-main-sm.jpg";
import historiaMainSmWebp from "../assets/images/Nuestra Historia/historia-main-sm.webp";
import historiaMainMdJpg from "../assets/images/Nuestra Historia/historia-main-md.jpg";
import historiaMainMdWebp from "../assets/images/Nuestra Historia/historia-main-md.webp";
import historiaMainLgJpg from "../assets/images/Nuestra Historia/historia-main-lg.jpg";
import historiaMainLgWebp from "../assets/images/Nuestra Historia/historia-main-lg.webp";
import historiaMainXlJpg from "../assets/images/Nuestra Historia/historia-main-xl.jpg";
import historiaMainXlWebp from "../assets/images/Nuestra Historia/historia-main-xl.webp";
import historiaMainXxlJpg from "../assets/images/Nuestra Historia/historia-main-xxl.jpg";
import historiaMainXxlWebp from "../assets/images/Nuestra Historia/historia-main-xxl.webp";
import historiaMainXxxlJpg from "../assets/images/Nuestra Historia/historia-main-xxxl.jpg";
import historiaMainXxxlWebp from "../assets/images/Nuestra Historia/historia-main-xxxl.webp";

import historiaSecondaryLgPng from "../assets/images/Nuestra Historia/historia-secondary-lg.png";
import historiaSecondaryLgWebp from "../assets/images/Nuestra Historia/historia-secondary-lg.webp";
import historiaSecondaryMdPng from "../assets/images/Nuestra Historia/historia-secondary-md.png";
import historiaSecondaryMdWebp from "../assets/images/Nuestra Historia/historia-secondary-md.webp";

import historia01SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-sm.jpg";
import historia01SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-sm.webp";
import historia01MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-md.jpg";
import historia01MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-md.webp";
import historia01LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-01-lg.jpg";
import historia01LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-01-lg.webp";
import historia02SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-sm.jpg";
import historia02SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-sm.webp";
import historia02MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-md.jpg";
import historia02MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-md.webp";
import historia02LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-02-lg.jpg";
import historia02LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-02-lg.webp";
import historia03SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-sm.jpg";
import historia03SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-sm.webp";
import historia03MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-md.jpg";
import historia03MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-md.webp";
import historia03LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-03-lg.jpg";
import historia03LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-03-lg.webp";
import historia04SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-sm.jpg";
import historia04SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-sm.webp";
import historia04MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-md.jpg";
import historia04MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-md.webp";
import historia04LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-04-lg.jpg";
import historia04LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-04-lg.webp";
import historia05SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-sm.jpg";
import historia05SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-sm.webp";
import historia05MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-md.jpg";
import historia05MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-md.webp";
import historia05LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-05-lg.jpg";
import historia05LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-05-lg.webp";
import historia06SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-sm.jpg";
import historia06SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-sm.webp";
import historia06MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-md.jpg";
import historia06MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-md.webp";
import historia06LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-06-lg.jpg";
import historia06LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-06-lg.webp";
import historia07SmJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-sm.jpg";
import historia07SmWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-sm.webp";
import historia07MdJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-md.jpg";
import historia07MdWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-md.webp";
import historia07LgJpg from "../assets/images/Nuestra Historia/nuestra-historia-07-lg.jpg";
import historia07LgWebp from "../assets/images/Nuestra Historia/nuestra-historia-07-lg.webp";

import fincaMainSmJpg from "../assets/images/La Finca/la-finca-main-sm.jpg";
import fincaMainSmWebp from "../assets/images/La Finca/la-finca-main-sm.webp";
import fincaMainMdJpg from "../assets/images/La Finca/la-finca-main-md.jpg";
import fincaMainMdWebp from "../assets/images/La Finca/la-finca-main-md.webp";
import fincaMainLgJpg from "../assets/images/La Finca/la-finca-main-lg.jpg";
import fincaMainLgWebp from "../assets/images/La Finca/la-finca-main-lg.webp";
import finca01SmJpg from "../assets/images/La Finca/la-finca-01-sm.jpg";
import finca01SmWebp from "../assets/images/La Finca/la-finca-01-sm.webp";
import finca01MdJpg from "../assets/images/La Finca/la-finca-01-md.jpg";
import finca01MdWebp from "../assets/images/La Finca/la-finca-01-md.webp";
import finca01LgJpg from "../assets/images/La Finca/la-finca-01-lg.jpg";
import finca01LgWebp from "../assets/images/La Finca/la-finca-01-lg.webp";
import finca02SmJpg from "../assets/images/La Finca/la-finca-02-sm.jpg";
import finca02SmWebp from "../assets/images/La Finca/la-finca-02-sm.webp";
import finca02MdJpg from "../assets/images/La Finca/la-finca-02-md.jpg";
import finca02MdWebp from "../assets/images/La Finca/la-finca-02-md.webp";
import finca02LgJpg from "../assets/images/La Finca/la-finca-02-lg.jpg";
import finca02LgWebp from "../assets/images/La Finca/la-finca-02-lg.webp";
import finca03SmJpg from "../assets/images/La Finca/la-finca-03-sm.jpg";
import finca03SmWebp from "../assets/images/La Finca/la-finca-03-sm.webp";
import finca03MdJpg from "../assets/images/La Finca/la-finca-03-md.jpg";
import finca03MdWebp from "../assets/images/La Finca/la-finca-03-md.webp";
import finca03LgJpg from "../assets/images/La Finca/la-finca-03-lg.jpg";
import finca03LgWebp from "../assets/images/La Finca/la-finca-03-lg.webp";
import finca04SmJpg from "../assets/images/La Finca/la-finca-04-sm.jpg";
import finca04SmWebp from "../assets/images/La Finca/la-finca-04-sm.webp";
import finca04MdJpg from "../assets/images/La Finca/la-finca-04-md.jpg";
import finca04MdWebp from "../assets/images/La Finca/la-finca-04-md.webp";
import finca04LgJpg from "../assets/images/La Finca/la-finca-04-lg.jpg";
import finca04LgWebp from "../assets/images/La Finca/la-finca-04-lg.webp";
import finca05SmJpg from "../assets/images/La Finca/la-finca-05-sm.jpg";
import finca05SmWebp from "../assets/images/La Finca/la-finca-05-sm.webp";
import finca05MdJpg from "../assets/images/La Finca/la-finca-05-md.jpg";
import finca05MdWebp from "../assets/images/La Finca/la-finca-05-md.webp";
import finca05LgJpg from "../assets/images/La Finca/la-finca-05-lg.jpg";
import finca05LgWebp from "../assets/images/La Finca/la-finca-05-lg.webp";

import equipoAlejandro from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Alejandro-Desktop.webp";
import equipoCelina from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Celina-Desktop.webp";
import equipoJony from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Jony-Desktop.webp";
import equipoSebas from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Sebas-Desktop.webp";
import equipoDiego from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Diego-Desktop.webp";
import placeholderAlejandro from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Alejandro-Desktop-ezgif.com-crop.jpg";
import placeholderCelina from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Celina-Desktop-ezgif.com-crop.jpg";
import placeholderJony from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Jony-Desktop-ezgif.com-crop.jpg";
import placeholderSebas from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Sebas-Desktop-ezgif.com-crop.jpg";
import placeholderDiego from "../assets/images/Equipo/04.2024-WebPielihueso-Img-Equipo-Diego-Desktop-ezgif.com-crop.jpg";

import contactoSmPng from "../assets/images/Contacto/contacto-sm.png";
import contactoSmWebp from "../assets/images/Contacto/contacto-sm.webp";
import contactoMdPng from "../assets/images/Contacto/contacto-md.png";
import contactoMdWebp from "../assets/images/Contacto/contacto-md.webp";
import contactoLgPng from "../assets/images/Contacto/contacto-lg.png";
import contactoLgWebp from "../assets/images/Contacto/contacto-lg.webp";
import contactoXlPng from "../assets/images/Contacto/contacto-xl.png";
import contactoXlWebp from "../assets/images/Contacto/contacto-xl.webp";

import comprarSmPng from "../assets/images/Donde Comprar/donde-comprar-sm.png";
import comprarSmWebp from "../assets/images/Donde Comprar/donde-comprar-sm.webp";
import comprarMdPng from "../assets/images/Donde Comprar/donde-comprar-md.png";
import comprarMdWebp from "../assets/images/Donde Comprar/donde-comprar-md.webp";
import comprarLgPng from "../assets/images/Donde Comprar/donde-comprar-lg.png";
import comprarLgWebp from "../assets/images/Donde Comprar/donde-comprar-lg.webp";
import comprarXlPng from "../assets/images/Donde Comprar/donde-comprar-xl.png";
import comprarXlWebp from "../assets/images/Donde Comprar/donde-comprar-xl.webp";

import faqSmPng from "../assets/images/FAQ/faq-sm.png";
import faqSmWebp from "../assets/images/FAQ/faq-sm.webp";
import faqMdPng from "../assets/images/FAQ/faq-md.png";
import faqMdWebp from "../assets/images/FAQ/faq-md.webp";
import faqLgPng from "../assets/images/FAQ/faq-lg.png";
import faqLgWebp from "../assets/images/FAQ/faq-lg.webp";
import faqXlPng from "../assets/images/FAQ/faq-xl.png";
import faqXlWebp from "../assets/images/FAQ/faq-xl.webp";

import iconExpand from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-expand.svg";
import iconClose from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-close.svg";
import iconArrowRight from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-arrow-right.svg";
import iconArrowLeft from "../assets/images/Logo and Icons/04.2024-WebPielihueso-Img-arrow-left.svg";

export const logoImg = logo;
export const iconInstagramImg = iconInstagram;
export const iconSmileyImg = iconSmiley;
export const iconSmileyWinkImg = iconSmileyWink;

export const home01SmJpgImg = home01SmJpg;
export const home01SmAvifImg = home01SmAvif;
export const home01MdJpgImg = home01MdJpg;
export const home01MdAvifImg = home01MdAvif;
export const home01LgJpgImg = home01LgJpg;
export const home01LgAvifImg = home01LgAvif;
export const home01XlJpgImg = home01XlJpg;
export const home01XlAvifImg = home01XlAvif;
export const home02SmJpgImg = home02SmJpg;
export const home02SmAvifImg = home02SmAvif;
export const home02MdJpgImg = home02MdJpg;
export const home02MdAvifImg = home02MdAvif;
export const home02LgJpgImg = home02LgJpg;
export const home02LgAvifImg = home02LgAvif;
export const home02XlJpgImg = home02XlJpg;
export const home02XlAvifImg = home02XlAvif;
export const home03SmJpgImg = home03SmJpg;
export const home03SmAvifImg = home03SmAvif;
export const home03MdJpgImg = home03MdJpg;
export const home03MdAvifImg = home03MdAvif;
export const home03LgJpgImg = home03LgJpg;
export const home03LgAvifImg = home03LgAvif;
export const home03XlJpgImg = home03XlJpg;
export const home03XlAvifImg = home03XlAvif;
export const home04SmJpgImg = home04SmJpg;
export const home04SmAvifImg = home04SmAvif;
export const home04MdJpgImg = home04MdJpg;
export const home04MdAvifImg = home04MdAvif;
export const home04LgJpgImg = home04LgJpg;
export const home04LgAvifImg = home04LgAvif;
export const home04XlJpgImg = home04XlJpg;
export const home04XlAvifImg = home04XlAvif;
export const home05SmJpgImg = home05SmJpg;
export const home05SmAvifImg = home05SmAvif;
export const home05MdJpgImg = home05MdJpg;
export const home05MdAvifImg = home05MdAvif;
export const home05LgJpgImg = home05LgJpg;
export const home05LgAvifImg = home05LgAvif;
export const home05XlJpgImg = home05XlJpg;
export const home05XlAvifImg = home05XlAvif;
export const home06SmJpgImg = home06SmJpg;
export const home06SmAvifImg = home06SmAvif;
export const home06MdJpgImg = home06MdJpg;
export const home06MdAvifImg = home06MdAvif;
export const home06LgJpgImg = home06LgJpg;
export const home06LgAvifImg = home06LgAvif;
export const home06XlJpgImg = home06XlJpg;
export const home06XlAvifImg = home06XlAvif;
export const home07SmJpgImg = home07SmJpg;
export const home07SmAvifImg = home07SmAvif;
export const home07MdJpgImg = home07MdJpg;
export const home07MdAvifImg = home07MdAvif;
export const home07LgJpgImg = home07LgJpg;
export const home07LgAvifImg = home07LgAvif;
export const home07XlJpgImg = home07XlJpg;
export const home07XlAvifImg = home07XlAvif;
export const home08SmJpgImg = home08SmJpg;
export const home08SmAvifImg = home08SmAvif;
export const home08MdJpgImg = home08MdJpg;
export const home08MdAvifImg = home08MdAvif;
export const home08LgJpgImg = home08LgJpg;
export const home08LgAvifImg = home08LgAvif;
export const home08XlJpgImg = home08XlJpg;
export const home08XlAvifImg = home08XlAvif;

export const vinosAnforaSmPngImg = vinosAnforaSmPng;
export const vinosAnforaContraSmPngImg = vinosAnforaContraSmPng;
export const vinosAnforaSmAvifImg = vinosAnforaSmAvif;
export const vinosAnforaContraSmAvifImg = vinosAnforaContraSmAvif;
export const vinosAnforaMdPngImg = vinosAnforaMdPng;
export const vinosAnforaContraMdPngImg = vinosAnforaContraMdPng;
export const vinosAnforaMdAvifImg = vinosAnforaMdAvif;
export const vinosAnforaContraMdAvifImg = vinosAnforaContraMdAvif;
export const vinosAnforaLgPngImg = vinosAnforaLgPng;
export const vinosAnforaContraLgPngImg = vinosAnforaContraLgPng;
export const vinosAnforaLgAvifImg = vinosAnforaLgAvif;
export const vinosAnforaContraLgAvifImg = vinosAnforaContraLgAvif;
export const vinosAnforaXlPngImg = vinosAnforaXlPng;
export const vinosAnforaContraXlPngImg = vinosAnforaContraXlPng;
export const vinosAnforaXlAvifImg = vinosAnforaXlAvif;
export const vinosAnforaContraXlAvifImg = vinosAnforaContraXlAvif;
export const vinosGalloSmPngImg = vinosGalloSmPng;
export const vinosGalloContraSmPngImg = vinosGalloContraSmPng;
export const vinosGalloSmAvifImg = vinosGalloSmAvif;
export const vinosGalloContraSmAvifImg = vinosGalloContraSmAvif;
export const vinosGalloMdPngImg = vinosGalloMdPng;
export const vinosGalloContraMdPngImg = vinosGalloContraMdPng;
export const vinosGalloMdAvifImg = vinosGalloMdAvif;
export const vinosGalloContraMdAvifImg = vinosGalloContraMdAvif;
export const vinosGalloLgPngImg = vinosGalloLgPng;
export const vinosGalloContraLgPngImg = vinosGalloContraLgPng;
export const vinosGalloLgAvifImg = vinosGalloLgAvif;
export const vinosGalloContraLgAvifImg = vinosGalloContraLgAvif;
export const vinosGalloXlPngImg = vinosGalloXlPng;
export const vinosGalloContraXlPngImg = vinosGalloContraXlPng;
export const vinosGalloXlAvifImg = vinosGalloXlAvif;
export const vinosGalloContraXlAvifImg = vinosGalloContraXlAvif;
export const vinosVillaSmPngImg = vinosVillaSmPng;
export const vinosVillaContraSmPngImg = vinosVillaContraSmPng;
export const vinosVillaSmAvifImg = vinosVillaSmAvif;
export const vinosVillaContraSmAvifImg = vinosVillaContraSmAvif;
export const vinosVillaMdPngImg = vinosVillaMdPng;
export const vinosVillaContraMdPngImg = vinosVillaContraMdPng;
export const vinosVillaMdAvifImg = vinosVillaMdAvif;
export const vinosVillaContraMdAvifImg = vinosVillaContraMdAvif;
export const vinosVillaLgPngImg = vinosVillaLgPng;
export const vinosVillaContraLgPngImg = vinosVillaContraLgPng;
export const vinosVillaLgAvifImg = vinosVillaLgAvif;
export const vinosVillaContraLgAvifImg = vinosVillaContraLgAvif;
export const vinosVillaXlPngImg = vinosVillaXlPng;
export const vinosVillaContraXlPngImg = vinosVillaContraXlPng;
export const vinosVillaXlAvifImg = vinosVillaXlAvif;
export const vinosVillaContraXlAvifImg = vinosVillaContraXlAvif;
export const vinosPintoSmPngImg = vinosPintoSmPng;
export const vinosPintoContraSmPngImg = vinosPintoContraSmPng;
export const vinosPintoSmAvifImg = vinosPintoSmAvif;
export const vinosPintoContraSmAvifImg = vinosPintoContraSmAvif;
export const vinosPintoMdPngImg = vinosPintoMdPng;
export const vinosPintoContraMdPngImg = vinosPintoContraMdPng;
export const vinosPintoMdAvifImg = vinosPintoMdAvif;
export const vinosPintoContraMdAvifImg = vinosPintoContraMdAvif;
export const vinosPintoLgPngImg = vinosPintoLgPng;
export const vinosPintoContraLgPngImg = vinosPintoContraLgPng;
export const vinosPintoLgAvifImg = vinosPintoLgAvif;
export const vinosPintoContraLgAvifImg = vinosPintoContraLgAvif;
export const vinosPintoXlPngImg = vinosPintoXlPng;
export const vinosPintoContraXlPngImg = vinosPintoContraXlPng;
export const vinosPintoXlAvifImg = vinosPintoXlAvif;
export const vinosPintoContraXlAvifImg = vinosPintoContraXlAvif;
export const vinosNaranjoSmPngImg = vinosNaranjoSmPng;
export const vinosNaranjoContraSmPngImg = vinosNaranjoContraSmPng;
export const vinosNaranjoSmAvifImg = vinosNaranjoSmAvif;
export const vinosNaranjoContraSmAvifImg = vinosNaranjoContraSmAvif;
export const vinosNaranjoMdPngImg = vinosNaranjoMdPng;
export const vinosNaranjoContraMdPngImg = vinosNaranjoContraMdPng;
export const vinosNaranjoMdAvifImg = vinosNaranjoMdAvif;
export const vinosNaranjoContraMdAvifImg = vinosNaranjoContraMdAvif;
export const vinosNaranjoLgPngImg = vinosNaranjoLgPng;
export const vinosNaranjoContraLgPngImg = vinosNaranjoContraLgPng;
export const vinosNaranjoLgAvifImg = vinosNaranjoLgAvif;
export const vinosNaranjoContraLgAvifImg = vinosNaranjoContraLgAvif;
export const vinosNaranjoXlPngImg = vinosNaranjoXlPng;
export const vinosNaranjoContraXlPngImg = vinosNaranjoContraXlPng;
export const vinosNaranjoXlAvifImg = vinosNaranjoXlAvif;
export const vinosNaranjoContraXlAvifImg = vinosNaranjoContraXlAvif;
export const vinosMalbecSmPngImg = vinosMalbecSmPng;
export const vinosMalbecContraSmPngImg = vinosMalbecContraSmPng;
export const vinosMalbecSmAvifImg = vinosMalbecSmAvif;
export const vinosMalbecContraSmAvifImg = vinosMalbecContraSmAvif;
export const vinosMalbecMdPngImg = vinosMalbecMdPng;
export const vinosMalbecContraMdPngImg = vinosMalbecContraMdPng;
export const vinosMalbecMdAvifImg = vinosMalbecMdAvif;
export const vinosMalbecContraMdAvifImg = vinosMalbecContraMdAvif;
export const vinosMalbecLgPngImg = vinosMalbecLgPng;
export const vinosMalbecContraLgPngImg = vinosMalbecContraLgPng;
export const vinosMalbecLgAvifImg = vinosMalbecLgAvif;
export const vinosMalbecContraLgAvifImg = vinosMalbecContraLgAvif;
export const vinosMalbecXlPngImg = vinosMalbecXlPng;
export const vinosMalbecContraXlPngImg = vinosMalbecContraXlPng;
export const vinosMalbecXlAvifImg = vinosMalbecXlAvif;
export const vinosMalbecContraXlAvifImg = vinosMalbecContraXlAvif;
export const vinosSenorSmPngImg = vinosSenorSmPng;
export const vinosSenorContraSmPngImg = vinosSenorContraSmPng;
export const vinosSenorSmAvifImg = vinosSenorSmAvif;
export const vinosSenorContraSmAvifImg = vinosSenorContraSmAvif;
export const vinosSenorMdPngImg = vinosSenorMdPng;
export const vinosSenorContraMdPngImg = vinosSenorContraMdPng;
export const vinosSenorMdAvifImg = vinosSenorMdAvif;
export const vinosSenorContraMdAvifImg = vinosSenorContraMdAvif;
export const vinosSenorLgPngImg = vinosSenorLgPng;
export const vinosSenorContraLgPngImg = vinosSenorContraLgPng;
export const vinosSenorLgAvifImg = vinosSenorLgAvif;
export const vinosSenorContraLgAvifImg = vinosSenorContraLgAvif;
export const vinosSenorXlPngImg = vinosSenorXlPng;
export const vinosSenorContraXlPngImg = vinosSenorContraXlPng;
export const vinosSenorXlAvifImg = vinosSenorXlAvif;
export const vinosSenorContraXlAvifImg = vinosSenorContraXlAvif;
export const vinosRosadoSmPngImg = vinosRosadoSmPng;
export const vinosRosadoContraSmPngImg = vinosRosadoContraSmPng;
export const vinosRosadoSmAvifImg = vinosRosadoSmAvif;
export const vinosRosadoContraSmAvifImg = vinosRosadoContraSmAvif;
export const vinosRosadoMdPngImg = vinosRosadoMdPng;
export const vinosRosadoContraMdPngImg = vinosRosadoContraMdPng;
export const vinosRosadoMdAvifImg = vinosRosadoMdAvif;
export const vinosRosadoContraMdAvifImg = vinosRosadoContraMdAvif;
export const vinosRosadoLgPngImg = vinosRosadoLgPng;
export const vinosRosadoContraLgPngImg = vinosRosadoContraLgPng;
export const vinosRosadoLgAvifImg = vinosRosadoLgAvif;
export const vinosRosadoContraLgAvifImg = vinosRosadoContraLgAvif;
export const vinosRosadoXlPngImg = vinosRosadoXlPng;
export const vinosRosadoContraXlPngImg = vinosRosadoContraXlPng;
export const vinosRosadoXlAvifImg = vinosRosadoXlAvif;
export const vinosRosadoContraXlAvifImg = vinosRosadoContraXlAvif;
export const vinosSaucesSmPngImg = vinosSaucesSmPng;
export const vinosSaucesContraSmPngImg = vinosSaucesContraSmPng;
export const vinosSaucesSmAvifImg = vinosSaucesSmAvif;
export const vinosSaucesContraSmAvifImg = vinosSaucesContraSmAvif;
export const vinosSaucesMdPngImg = vinosSaucesMdPng;
export const vinosSaucesContraMdPngImg = vinosSaucesContraMdPng;
export const vinosSaucesMdAvifImg = vinosSaucesMdAvif;
export const vinosSaucesContraMdAvifImg = vinosSaucesContraMdAvif;
export const vinosSaucesLgPngImg = vinosSaucesLgPng;
export const vinosSaucesContraLgPngImg = vinosSaucesContraLgPng;
export const vinosSaucesLgAvifImg = vinosSaucesLgAvif;
export const vinosSaucesContraLgAvifImg = vinosSaucesContraLgAvif;
export const vinosSaucesXlPngImg = vinosSaucesXlPng;
export const vinosSaucesContraXlPngImg = vinosSaucesContraXlPng;
export const vinosSaucesXlAvifImg = vinosSaucesXlAvif;
export const vinosSaucesContraXlAvifImg = vinosSaucesContraXlAvif;
export const vinosBlancoSmPngImg = vinosBlancoSmPng;
export const vinosBlancoContraSmPngImg = vinosBlancoContraSmPng;
export const vinosBlancoSmAvifImg = vinosBlancoSmAvif;
export const vinosBlancoContraSmAvifImg = vinosBlancoContraSmAvif;
export const vinosBlancoMdPngImg = vinosBlancoMdPng;
export const vinosBlancoContraMdPngImg = vinosBlancoContraMdPng;
export const vinosBlancoMdAvifImg = vinosBlancoMdAvif;
export const vinosBlancoContraMdAvifImg = vinosBlancoContraMdAvif;
export const vinosBlancoLgPngImg = vinosBlancoLgPng;
export const vinosBlancoContraLgPngImg = vinosBlancoContraLgPng;
export const vinosBlancoLgAvifImg = vinosBlancoLgAvif;
export const vinosBlancoContraLgAvifImg = vinosBlancoContraLgAvif;
export const vinosBlancoXlPngImg = vinosBlancoXlPng;
export const vinosBlancoContraXlPngImg = vinosBlancoContraXlPng;
export const vinosBlancoXlAvifImg = vinosBlancoXlAvif;
export const vinosBlancoContraXlAvifImg = vinosBlancoContraXlAvif;

export const historiaMainSmJpgImg = historiaMainSmJpg;
export const historiaMainSmWebpImg = historiaMainSmWebp;
export const historiaMainMdJpgImg = historiaMainMdJpg;
export const historiaMainMdWebpImg = historiaMainMdWebp;
export const historiaMainLgJpgImg = historiaMainLgJpg;
export const historiaMainLgWebpImg = historiaMainLgWebp;
export const historiaMainXlJpgImg = historiaMainXlJpg;
export const historiaMainXlWebpImg = historiaMainXlWebp;
export const historiaMainXxlJpgImg = historiaMainXxlJpg;
export const historiaMainXxlWebpImg = historiaMainXxlWebp;
export const historiaMainXxxlJpgImg = historiaMainXxxlJpg;
export const historiaMainXxxlWebpImg = historiaMainXxxlWebp;

export const historia01SmJpgImg = historia01SmJpg;
export const historia01MdWebpImg = historia01MdWebp;
export const historia01LgJpgImg = historia01LgJpg;
export const historia01SmWebpImg = historia01SmWebp;
export const historia01MdJpgImg = historia01MdJpg;
export const historia01LgWebpImg = historia01LgWebp;
export const historia02SmJpgImg = historia02SmJpg;
export const historia02MdWebpImg = historia02MdWebp;
export const historia02LgJpgImg = historia02LgJpg;
export const historia02SmWebpImg = historia02SmWebp;
export const historia02MdJpgImg = historia02MdJpg;
export const historia02LgWebpImg = historia02LgWebp;
export const historia03SmJpgImg = historia03SmJpg;
export const historia03MdWebpImg = historia03MdWebp;
export const historia03LgJpgImg = historia03LgJpg;
export const historia03SmWebpImg = historia03SmWebp;
export const historia03MdJpgImg = historia03MdJpg;
export const historia03LgWebpImg = historia03LgWebp;
export const historia04SmJpgImg = historia04SmJpg;
export const historia04MdWebpImg = historia04MdWebp;
export const historia04LgJpgImg = historia04LgJpg;
export const historia04SmWebpImg = historia04SmWebp;
export const historia04MdJpgImg = historia04MdJpg;
export const historia04LgWebpImg = historia04LgWebp;
export const historia05SmJpgImg = historia05SmJpg;
export const historia05MdWebpImg = historia05MdWebp;
export const historia05LgJpgImg = historia05LgJpg;
export const historia05SmWebpImg = historia05SmWebp;
export const historia05MdJpgImg = historia05MdJpg;
export const historia05LgWebpImg = historia05LgWebp;
export const historia06SmJpgImg = historia06SmJpg;
export const historia06MdWebpImg = historia06MdWebp;
export const historia06LgJpgImg = historia06LgJpg;
export const historia06SmWebpImg = historia06SmWebp;
export const historia06MdJpgImg = historia06MdJpg;
export const historia06LgWebpImg = historia06LgWebp;
export const historia07SmJpgImg = historia07SmJpg;
export const historia07MdWebpImg = historia07MdWebp;
export const historia07LgJpgImg = historia07LgJpg;
export const historia07SmWebpImg = historia07SmWebp;
export const historia07MdJpgImg = historia07MdJpg;
export const historia07LgWebpImg = historia07LgWebp;

export const historiaSecondaryMdPngImg = historiaSecondaryMdPng;
export const historiaSecondaryMdWebpImg = historiaSecondaryMdWebp;
export const historiaSecondaryLgPngImg = historiaSecondaryLgPng;
export const historiaSecondaryLgWebpImg = historiaSecondaryLgWebp;

export const fincaMainSmJpgImg = fincaMainSmJpg;
export const fincaMainSmWebpImg = fincaMainSmWebp;
export const fincaMainMdJpgImg = fincaMainMdJpg;
export const fincaMainMdWebpImg = fincaMainMdWebp;
export const fincaMainLgJpgImg = fincaMainLgJpg;
export const fincaMainLgWebpImg = fincaMainLgWebp;
export const finca01SmJpgImg = finca01SmJpg;
export const finca01SmWebpImg = finca01SmWebp;
export const finca01MdJpgImg = finca01MdJpg;
export const finca01MdWebpImg = finca01MdWebp;
export const finca01LgJpgImg = finca01LgJpg;
export const finca01LgWebpImg = finca01LgWebp;
export const finca02SmJpgImg = finca02SmJpg;
export const finca02SmWebpImg = finca02SmWebp;
export const finca02MdJpgImg = finca02MdJpg;
export const finca02MdWebpImg = finca02MdWebp;
export const finca02LgJpgImg = finca02LgJpg;
export const finca02LgWebpImg = finca02LgWebp;
export const finca03SmJpgImg = finca03SmJpg;
export const finca03SmWebpImg = finca03SmWebp;
export const finca03MdJpgImg = finca03MdJpg;
export const finca03MdWebpImg = finca03MdWebp;
export const finca03LgJpgImg = finca03LgJpg;
export const finca03LgWebpImg = finca03LgWebp;
export const finca04SmJpgImg = finca04SmJpg;
export const finca04SmWebpImg = finca04SmWebp;
export const finca04MdJpgImg = finca04MdJpg;
export const finca04MdWebpImg = finca04MdWebp;
export const finca04LgJpgImg = finca04LgJpg;
export const finca04LgWebpImg = finca04LgWebp;
export const finca05SmJpgImg = finca05SmJpg;
export const finca05SmWebpImg = finca05SmWebp;
export const finca05MdJpgImg = finca05MdJpg;
export const finca05MdWebpImg = finca05MdWebp;
export const finca05LgJpgImg = finca05LgJpg;
export const finca05LgWebpImg = finca05LgWebp;

export const equipoAlejandroImg = equipoAlejandro;
export const equipoCelinaImg = equipoCelina;
export const equipoJonyImg = equipoJony;
export const equipoSebasImg = equipoSebas;
export const equipoDiegoImg = equipoDiego;
export const placeholderAlejandroImg = placeholderAlejandro;
export const placeholderCelinaImg = placeholderCelina;
export const placeholderJonyImg = placeholderJony;
export const placeholderSebasImg = placeholderSebas;
export const placeholderDiegoImg = placeholderDiego;

export const contactoSmPngImg = contactoSmPng;
export const contactoSmWebpImg = contactoSmWebp;
export const contactoMdPngImg = contactoMdPng;
export const contactoMdWebpImg = contactoMdWebp;
export const contactoLgPngImg = contactoLgPng;
export const contactoLgWebpImg = contactoLgWebp;
export const contactoXlPngImg = contactoXlPng;
export const contactoXlWebpImg = contactoXlWebp;

export const comprarSmPngImg = comprarSmPng;
export const comprarSmWebpImg = comprarSmWebp;
export const comprarMdPngImg = comprarMdPng;
export const comprarMdWebpImg = comprarMdWebp;
export const comprarLgPngImg = comprarLgPng;
export const comprarLgWebpImg = comprarLgWebp;
export const comprarXlPngImg = comprarXlPng;
export const comprarXlWebpImg = comprarXlWebp;

export const faqSmPngImg = faqSmPng;
export const faqSmWebpImg = faqSmWebp;
export const faqMdPngImg = faqMdPng;
export const faqMdWebpImg = faqMdWebp;
export const faqLgPngImg = faqLgPng;
export const faqLgWebpImg = faqLgWebp;
export const faqXlPngImg = faqXlPng;
export const faqXlWebpImg = faqXlWebp;

export const iconExpandImg = iconExpand;
export const iconCloseImg = iconClose;
export const iconArrowRightImg = iconArrowRight;
export const iconArrowLeftImg = iconArrowLeft;
